// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: idm/v1/idm.proto

// Пакет idm.v1 — контракт сервиса IDM (права/роли). Источник правды для
// внутренних вызовов gateway↔idm (ADR-0002). В MVP — минимальный RBAC через
// CheckAccess; интерфейс целевой, наполнение ролей — позже.

package idmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckAccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subject — идентификатор пользователя/сервиса (например, sub из JWT).
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// resource — целевой ресурс (например, "project:acme").
	Resource string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// action — действие (например, "create", "transfer", "decommission").
	Action        string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessRequest) Reset() {
	*x = CheckAccessRequest{}
	mi := &file_idm_v1_idm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessRequest) ProtoMessage() {}

func (x *CheckAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckAccessRequest) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAccessRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CheckAccessRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckAccessRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type CheckAccessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// allowed — итоговое решение политики.
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// reason — машинно-читаемая причина отказа (для логов/отладки), необязательна.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessResponse) Reset() {
	*x = CheckAccessResponse{}
	mi := &file_idm_v1_idm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessResponse) ProtoMessage() {}

func (x *CheckAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckAccessResponse) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAccessResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckAccessResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_idm_v1_idm_proto protoreflect.FileDescriptor

const file_idm_v1_idm_proto_rawDesc = "" +
	"\n" +
	"\x10idm/v1/idm.proto\x12\x06idm.v1\"b\n" +
	"\x12CheckAccessRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"G\n" +
	"\x13CheckAccessResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2W\n" +
	"\rAccessService\x12F\n" +
	"\vCheckAccess\x12\x1a.idm.v1.CheckAccessRequest\x1a\x1b.idm.v1.CheckAccessResponseB,Z*github.com/YuriB9/idp/pkg/api/idm/v1;idmv1b\x06proto3"

var (
	file_idm_v1_idm_proto_rawDescOnce sync.Once
	file_idm_v1_idm_proto_rawDescData []byte
)

func file_idm_v1_idm_proto_rawDescGZIP() []byte {
	file_idm_v1_idm_proto_rawDescOnce.Do(func() {
		file_idm_v1_idm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idm_v1_idm_proto_rawDesc), len(file_idm_v1_idm_proto_rawDesc)))
	})
	return file_idm_v1_idm_proto_rawDescData
}

var file_idm_v1_idm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_idm_v1_idm_proto_goTypes = []any{
	(*CheckAccessRequest)(nil),  // 0: idm.v1.CheckAccessRequest
	(*CheckAccessResponse)(nil), // 1: idm.v1.CheckAccessResponse
}
var file_idm_v1_idm_proto_depIdxs = []int32{
	0, // 0: idm.v1.AccessService.CheckAccess:input_type -> idm.v1.CheckAccessRequest
	1, // 1: idm.v1.AccessService.CheckAccess:output_type -> idm.v1.CheckAccessResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idm_v1_idm_proto_init() }
func file_idm_v1_idm_proto_init() {
	if File_idm_v1_idm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idm_v1_idm_proto_rawDesc), len(file_idm_v1_idm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idm_v1_idm_proto_goTypes,
		DependencyIndexes: file_idm_v1_idm_proto_depIdxs,
		MessageInfos:      file_idm_v1_idm_proto_msgTypes,
	}.Build()
	File_idm_v1_idm_proto = out.File
	file_idm_v1_idm_proto_goTypes = nil
	file_idm_v1_idm_proto_depIdxs = nil
}
