// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: idm/v1/idm.proto

// Пакет idm.v1 — контракт сервиса IDM (права/роли). Источник правды для
// внутренних вызовов gateway↔idm (ADR-0002). В MVP — минимальный RBAC через
// CheckAccess; интерфейс целевой, наполнение ролей — позже.

package idmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubjectIdentity — идентичность субъекта из каталога Keycloak.
type SubjectIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subject — канонический ключ субъекта = sub (UUID Keycloak); тот же, что в
	// subject_roles.subject и auth.Claims.Subject.
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// username — имя входа (preferred_username); ключом авторизации НЕ является.
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// email — адрес электронной почты пользователя.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// display_name — отображаемое имя (имя + фамилия), если задано.
	DisplayName string `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// enabled — активен ли пользователь в realm.
	Enabled bool `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// found — найден ли субъект в каталоге; false → «осиротевший» (роль есть, в
	// каталоге нет).
	Found         bool `protobuf:"varint,6,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectIdentity) Reset() {
	*x = SubjectIdentity{}
	mi := &file_idm_v1_idm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectIdentity) ProtoMessage() {}

func (x *SubjectIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectIdentity.ProtoReflect.Descriptor instead.
func (*SubjectIdentity) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{0}
}

func (x *SubjectIdentity) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SubjectIdentity) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SubjectIdentity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SubjectIdentity) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *SubjectIdentity) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SubjectIdentity) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type SearchSubjectsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// query — строка поиска (username/email/имя); непустая, не короче минимума.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// cursor — непрозрачный курсор страницы (поверх offset Keycloak); пусто —
	// первая страница.
	Cursor string `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// page_size — желаемый размер страницы; сервер клампит к пределу (0 → дефолт).
	PageSize      int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSubjectsRequest) Reset() {
	*x = SearchSubjectsRequest{}
	mi := &file_idm_v1_idm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSubjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSubjectsRequest) ProtoMessage() {}

func (x *SearchSubjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSubjectsRequest.ProtoReflect.Descriptor instead.
func (*SearchSubjectsRequest) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{1}
}

func (x *SearchSubjectsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchSubjectsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *SearchSubjectsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchSubjectsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subjects — страница найденных идентичностей (found=true).
	Subjects []*SubjectIdentity `protobuf:"bytes,1,rep,name=subjects,proto3" json:"subjects,omitempty"`
	// next_cursor — непрозрачный курсор следующей страницы (пусто — больше нет).
	NextCursor    string `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSubjectsResponse) Reset() {
	*x = SearchSubjectsResponse{}
	mi := &file_idm_v1_idm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSubjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSubjectsResponse) ProtoMessage() {}

func (x *SearchSubjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSubjectsResponse.ProtoReflect.Descriptor instead.
func (*SearchSubjectsResponse) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{2}
}

func (x *SearchSubjectsResponse) GetSubjects() []*SubjectIdentity {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *SearchSubjectsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type ResolveSubjectsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subjects — канонические ключи (sub) для резолва (непустой список).
	Subjects      []string `protobuf:"bytes,1,rep,name=subjects,proto3" json:"subjects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSubjectsRequest) Reset() {
	*x = ResolveSubjectsRequest{}
	mi := &file_idm_v1_idm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSubjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSubjectsRequest) ProtoMessage() {}

func (x *ResolveSubjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSubjectsRequest.ProtoReflect.Descriptor instead.
func (*ResolveSubjectsRequest) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveSubjectsRequest) GetSubjects() []string {
	if x != nil {
		return x.Subjects
	}
	return nil
}

type ResolveSubjectsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subjects — идентичности в том же составе ключей; отсутствующие — found=false.
	Subjects      []*SubjectIdentity `protobuf:"bytes,1,rep,name=subjects,proto3" json:"subjects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSubjectsResponse) Reset() {
	*x = ResolveSubjectsResponse{}
	mi := &file_idm_v1_idm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSubjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSubjectsResponse) ProtoMessage() {}

func (x *ResolveSubjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSubjectsResponse.ProtoReflect.Descriptor instead.
func (*ResolveSubjectsResponse) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveSubjectsResponse) GetSubjects() []*SubjectIdentity {
	if x != nil {
		return x.Subjects
	}
	return nil
}

// Role — роль каталога. Стабильный идентификатор роли — её name (им же оперируют
// AssignRole/RevokeRole); внутренний id (UUID) наружу не отдаётся.
type Role struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name — человекочитаемое уникальное имя роли.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// system — признак системной (сидированной) роли: такие роли защищены от
	// удаления и правки набора прав через API (ADR-0015). Поле аддитивно
	// (wire-совместимо): старые клиенты, не знающие о нём, видят false.
	System        bool `protobuf:"varint,2,opt,name=system,proto3" json:"system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_idm_v1_idm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{5}
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetSystem() bool {
	if x != nil {
		return x.System
	}
	return false
}

// Permission — право: пара (action, resource), сравнение строгое.
type Permission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// action — действие (например, "read", "write", "create", "manage").
	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	// resource — целевой ресурс (например, "iam:global", "project:demo").
	Resource string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// system — признак системного (сидированного) права: защищено от удаления
	// через API (ADR-0015). Поле аддитивно (wire-совместимо).
	System        bool `protobuf:"varint,3,opt,name=system,proto3" json:"system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_idm_v1_idm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{6}
}

func (x *Permission) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Permission) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Permission) GetSystem() bool {
	if x != nil {
		return x.System
	}
	return false
}

// SubjectRoles — субъект и набор имён его ролей.
type SubjectRoles struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subject — идентификатор субъекта (sub из JWT).
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// roles — имена ролей субъекта.
	Roles         []string `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectRoles) Reset() {
	*x = SubjectRoles{}
	mi := &file_idm_v1_idm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectRoles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectRoles) ProtoMessage() {}

func (x *SubjectRoles) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectRoles.ProtoReflect.Descriptor instead.
func (*SubjectRoles) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{7}
}

func (x *SubjectRoles) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SubjectRoles) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ListRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_idm_v1_idm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{8}
}

type ListRolesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// roles — полный список ролей каталога.
	Roles         []*Role `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_idm_v1_idm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{9}
}

func (x *ListRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ListPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsRequest) Reset() {
	*x = ListPermissionsRequest{}
	mi := &file_idm_v1_idm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsRequest) ProtoMessage() {}

func (x *ListPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{10}
}

type ListPermissionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// permissions — полный список прав каталога.
	Permissions   []*Permission `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsResponse) Reset() {
	*x = ListPermissionsResponse{}
	mi := &file_idm_v1_idm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsResponse) ProtoMessage() {}

func (x *ListPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{11}
}

func (x *ListPermissionsResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type GetRolePermissionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role — имя роли, чьи права запрашиваются.
	Role          string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePermissionsRequest) Reset() {
	*x = GetRolePermissionsRequest{}
	mi := &file_idm_v1_idm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionsRequest) ProtoMessage() {}

func (x *GetRolePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetRolePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{12}
}

func (x *GetRolePermissionsRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GetRolePermissionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// permissions — права запрошенной роли.
	Permissions   []*Permission `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePermissionsResponse) Reset() {
	*x = GetRolePermissionsResponse{}
	mi := &file_idm_v1_idm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionsResponse) ProtoMessage() {}

func (x *GetRolePermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetRolePermissionsResponse) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{13}
}

func (x *GetRolePermissionsResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type ListSubjectsWithRolesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// page_size — желаемый размер страницы; сервер клампит к пределу (0 → дефолт).
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// page_token — непрозрачный курсор keyset (пусто — первая страница).
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubjectsWithRolesRequest) Reset() {
	*x = ListSubjectsWithRolesRequest{}
	mi := &file_idm_v1_idm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubjectsWithRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubjectsWithRolesRequest) ProtoMessage() {}

func (x *ListSubjectsWithRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubjectsWithRolesRequest.ProtoReflect.Descriptor instead.
func (*ListSubjectsWithRolesRequest) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{14}
}

func (x *ListSubjectsWithRolesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSubjectsWithRolesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListSubjectsWithRolesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subjects — страница субъектов с их ролями (ASC по subject).
	Subjects []*SubjectRoles `protobuf:"bytes,1,rep,name=subjects,proto3" json:"subjects,omitempty"`
	// next_page_token — курсор следующей страницы (пусто — страниц больше нет).
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubjectsWithRolesResponse) Reset() {
	*x = ListSubjectsWithRolesResponse{}
	mi := &file_idm_v1_idm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubjectsWithRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubjectsWithRolesResponse) ProtoMessage() {}

func (x *ListSubjectsWithRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubjectsWithRolesResponse.ProtoReflect.Descriptor instead.
func (*ListSubjectsWithRolesResponse) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{15}
}

func (x *ListSubjectsWithRolesResponse) GetSubjects() []*SubjectRoles {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *ListSubjectsWithRolesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetSubjectRolesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subject — идентификатор субъекта.
	Subject       string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubjectRolesRequest) Reset() {
	*x = GetSubjectRolesRequest{}
	mi := &file_idm_v1_idm_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubjectRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubjectRolesRequest) ProtoMessage() {}

func (x *GetSubjectRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubjectRolesRequest.ProtoReflect.Descriptor instead.
func (*GetSubjectRolesRequest) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{16}
}

func (x *GetSubjectRolesRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type GetSubjectRolesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// roles — имена ролей субъекта (пусто, если ролей нет).
	Roles         []string `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubjectRolesResponse) Reset() {
	*x = GetSubjectRolesResponse{}
	mi := &file_idm_v1_idm_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubjectRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubjectRolesResponse) ProtoMessage() {}

func (x *GetSubjectRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubjectRolesResponse.ProtoReflect.Descriptor instead.
func (*GetSubjectRolesResponse) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{17}
}

func (x *GetSubjectRolesResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type CheckAccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subject — идентификатор пользователя/сервиса (например, sub из JWT).
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// resource — целевой ресурс (например, "project:acme").
	Resource string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// action — действие (например, "create", "transfer", "decommission").
	Action        string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessRequest) Reset() {
	*x = CheckAccessRequest{}
	mi := &file_idm_v1_idm_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessRequest) ProtoMessage() {}

func (x *CheckAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckAccessRequest) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{18}
}

func (x *CheckAccessRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CheckAccessRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckAccessRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type CheckAccessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// allowed — итоговое решение политики.
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// reason — машинно-читаемая причина отказа (для логов/отладки), необязательна.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessResponse) Reset() {
	*x = CheckAccessResponse{}
	mi := &file_idm_v1_idm_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessResponse) ProtoMessage() {}

func (x *CheckAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckAccessResponse) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{19}
}

func (x *CheckAccessResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckAccessResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AssignRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subject — идентификатор субъекта (sub из JWT).
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// role — имя роли (например, "owner:project:demo").
	Role          string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleRequest) Reset() {
	*x = AssignRoleRequest{}
	mi := &file_idm_v1_idm_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleRequest) ProtoMessage() {}

func (x *AssignRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleRequest) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{20}
}

func (x *AssignRoleRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AssignRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AssignRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleResponse) Reset() {
	*x = AssignRoleResponse{}
	mi := &file_idm_v1_idm_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleResponse) ProtoMessage() {}

func (x *AssignRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleResponse.ProtoReflect.Descriptor instead.
func (*AssignRoleResponse) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{21}
}

type RevokeRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// subject — идентификатор субъекта.
	Subject string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// role — имя роли.
	Role          string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRoleRequest) Reset() {
	*x = RevokeRoleRequest{}
	mi := &file_idm_v1_idm_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRoleRequest) ProtoMessage() {}

func (x *RevokeRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRoleRequest.ProtoReflect.Descriptor instead.
func (*RevokeRoleRequest) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{22}
}

func (x *RevokeRoleRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RevokeRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RevokeRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRoleResponse) Reset() {
	*x = RevokeRoleResponse{}
	mi := &file_idm_v1_idm_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRoleResponse) ProtoMessage() {}

func (x *RevokeRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRoleResponse.ProtoReflect.Descriptor instead.
func (*RevokeRoleResponse) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{23}
}

// RolePermissions — роль и актуальный набор её прав (ответ attach/detach).
type RolePermissions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role — имя роли.
	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// permissions — текущий набор прав роли после операции.
	Permissions   []*Permission `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermissions) Reset() {
	*x = RolePermissions{}
	mi := &file_idm_v1_idm_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissions) ProtoMessage() {}

func (x *RolePermissions) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissions.ProtoReflect.Descriptor instead.
func (*RolePermissions) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{24}
}

func (x *RolePermissions) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RolePermissions) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type CreateRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name — имя создаваемой роли (непустое, уникальное).
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_idm_v1_idm_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{25}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateRoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role — созданная роль (system=false).
	Role          *Role `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_idm_v1_idm_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{26}
}

func (x *CreateRoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type DeleteRoleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name — имя удаляемой роли.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_idm_v1_idm_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleResponse) Reset() {
	*x = DeleteRoleResponse{}
	mi := &file_idm_v1_idm_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleResponse) ProtoMessage() {}

func (x *DeleteRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{28}
}

type CreatePermissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// action — действие создаваемого права (непустое).
	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	// resource — ресурс создаваемого права (непустой).
	Resource      string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionRequest) Reset() {
	*x = CreatePermissionRequest{}
	mi := &file_idm_v1_idm_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionRequest) ProtoMessage() {}

func (x *CreatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionRequest.ProtoReflect.Descriptor instead.
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{29}
}

func (x *CreatePermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CreatePermissionRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type CreatePermissionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// permission — созданное право (system=false).
	Permission    *Permission `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionResponse) Reset() {
	*x = CreatePermissionResponse{}
	mi := &file_idm_v1_idm_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionResponse) ProtoMessage() {}

func (x *CreatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionResponse.ProtoReflect.Descriptor instead.
func (*CreatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{30}
}

func (x *CreatePermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type DeletePermissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// action — действие удаляемого права.
	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	// resource — ресурс удаляемого права.
	Resource      string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionRequest) Reset() {
	*x = DeletePermissionRequest{}
	mi := &file_idm_v1_idm_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionRequest) ProtoMessage() {}

func (x *DeletePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionRequest.ProtoReflect.Descriptor instead.
func (*DeletePermissionRequest) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{31}
}

func (x *DeletePermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DeletePermissionRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type DeletePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionResponse) Reset() {
	*x = DeletePermissionResponse{}
	mi := &file_idm_v1_idm_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionResponse) ProtoMessage() {}

func (x *DeletePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionResponse.ProtoReflect.Descriptor instead.
func (*DeletePermissionResponse) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{32}
}

type AttachPermissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role — имя роли, к которой прикрепляется право.
	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// action — действие прикрепляемого права.
	Action string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	// resource — ресурс прикрепляемого права.
	Resource      string `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachPermissionRequest) Reset() {
	*x = AttachPermissionRequest{}
	mi := &file_idm_v1_idm_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachPermissionRequest) ProtoMessage() {}

func (x *AttachPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachPermissionRequest.ProtoReflect.Descriptor instead.
func (*AttachPermissionRequest) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{33}
}

func (x *AttachPermissionRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AttachPermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AttachPermissionRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type AttachPermissionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role_permissions — актуальный набор прав роли после прикрепления.
	RolePermissions *RolePermissions `protobuf:"bytes,1,opt,name=role_permissions,json=rolePermissions,proto3" json:"role_permissions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AttachPermissionResponse) Reset() {
	*x = AttachPermissionResponse{}
	mi := &file_idm_v1_idm_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachPermissionResponse) ProtoMessage() {}

func (x *AttachPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachPermissionResponse.ProtoReflect.Descriptor instead.
func (*AttachPermissionResponse) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{34}
}

func (x *AttachPermissionResponse) GetRolePermissions() *RolePermissions {
	if x != nil {
		return x.RolePermissions
	}
	return nil
}

type DetachPermissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role — имя роли, от которой открепляется право.
	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// action — действие открепляемого права.
	Action string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	// resource — ресурс открепляемого права.
	Resource      string `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachPermissionRequest) Reset() {
	*x = DetachPermissionRequest{}
	mi := &file_idm_v1_idm_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachPermissionRequest) ProtoMessage() {}

func (x *DetachPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachPermissionRequest.ProtoReflect.Descriptor instead.
func (*DetachPermissionRequest) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{35}
}

func (x *DetachPermissionRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *DetachPermissionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DetachPermissionRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type DetachPermissionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// role_permissions — актуальный набор прав роли после открепления.
	RolePermissions *RolePermissions `protobuf:"bytes,1,opt,name=role_permissions,json=rolePermissions,proto3" json:"role_permissions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DetachPermissionResponse) Reset() {
	*x = DetachPermissionResponse{}
	mi := &file_idm_v1_idm_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachPermissionResponse) ProtoMessage() {}

func (x *DetachPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idm_v1_idm_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachPermissionResponse.ProtoReflect.Descriptor instead.
func (*DetachPermissionResponse) Descriptor() ([]byte, []int) {
	return file_idm_v1_idm_proto_rawDescGZIP(), []int{36}
}

func (x *DetachPermissionResponse) GetRolePermissions() *RolePermissions {
	if x != nil {
		return x.RolePermissions
	}
	return nil
}

var File_idm_v1_idm_proto protoreflect.FileDescriptor

const file_idm_v1_idm_proto_rawDesc = "" +
	"\n" +
	"\x10idm/v1/idm.proto\x12\x06idm.v1\"\xb0\x01\n" +
	"\x0fSubjectIdentity\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x14\n" +
	"\x05found\x18\x06 \x01(\bR\x05found\"b\n" +
	"\x15SearchSubjectsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"n\n" +
	"\x16SearchSubjectsResponse\x123\n" +
	"\bsubjects\x18\x01 \x03(\v2\x17.idm.v1.SubjectIdentityR\bsubjects\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"4\n" +
	"\x16ResolveSubjectsRequest\x12\x1a\n" +
	"\bsubjects\x18\x01 \x03(\tR\bsubjects\"N\n" +
	"\x17ResolveSubjectsResponse\x123\n" +
	"\bsubjects\x18\x01 \x03(\v2\x17.idm.v1.SubjectIdentityR\bsubjects\"2\n" +
	"\x04Role\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06system\x18\x02 \x01(\bR\x06system\"X\n" +
	"\n" +
	"Permission\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06system\x18\x03 \x01(\bR\x06system\">\n" +
	"\fSubjectRoles\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\"\x12\n" +
	"\x10ListRolesRequest\"7\n" +
	"\x11ListRolesResponse\x12\"\n" +
	"\x05roles\x18\x01 \x03(\v2\f.idm.v1.RoleR\x05roles\"\x18\n" +
	"\x16ListPermissionsRequest\"O\n" +
	"\x17ListPermissionsResponse\x124\n" +
	"\vpermissions\x18\x01 \x03(\v2\x12.idm.v1.PermissionR\vpermissions\"/\n" +
	"\x19GetRolePermissionsRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\"R\n" +
	"\x1aGetRolePermissionsResponse\x124\n" +
	"\vpermissions\x18\x01 \x03(\v2\x12.idm.v1.PermissionR\vpermissions\"Z\n" +
	"\x1cListSubjectsWithRolesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"y\n" +
	"\x1dListSubjectsWithRolesResponse\x120\n" +
	"\bsubjects\x18\x01 \x03(\v2\x14.idm.v1.SubjectRolesR\bsubjects\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"2\n" +
	"\x16GetSubjectRolesRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\"/\n" +
	"\x17GetSubjectRolesResponse\x12\x14\n" +
	"\x05roles\x18\x01 \x03(\tR\x05roles\"b\n" +
	"\x12CheckAccessRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"G\n" +
	"\x13CheckAccessResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"A\n" +
	"\x11AssignRoleRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"\x14\n" +
	"\x12AssignRoleResponse\"A\n" +
	"\x11RevokeRoleRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"\x14\n" +
	"\x12RevokeRoleResponse\"[\n" +
	"\x0fRolePermissions\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x124\n" +
	"\vpermissions\x18\x02 \x03(\v2\x12.idm.v1.PermissionR\vpermissions\"'\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"6\n" +
	"\x12CreateRoleResponse\x12 \n" +
	"\x04role\x18\x01 \x01(\v2\f.idm.v1.RoleR\x04role\"'\n" +
	"\x11DeleteRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x14\n" +
	"\x12DeleteRoleResponse\"M\n" +
	"\x17CreatePermissionRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\"N\n" +
	"\x18CreatePermissionResponse\x122\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x12.idm.v1.PermissionR\n" +
	"permission\"M\n" +
	"\x17DeletePermissionRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\"\x1a\n" +
	"\x18DeletePermissionResponse\"a\n" +
	"\x17AttachPermissionRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\"^\n" +
	"\x18AttachPermissionResponse\x12B\n" +
	"\x10role_permissions\x18\x01 \x01(\v2\x17.idm.v1.RolePermissionsR\x0frolePermissions\"a\n" +
	"\x17DetachPermissionRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\"^\n" +
	"\x18DetachPermissionResponse\x12B\n" +
	"\x10role_permissions\x18\x01 \x01(\v2\x17.idm.v1.RolePermissionsR\x0frolePermissions2W\n" +
	"\rAccessService\x12F\n" +
	"\vCheckAccess\x12\x1a.idm.v1.CheckAccessRequest\x1a\x1b.idm.v1.CheckAccessResponse2\x9c\x01\n" +
	"\x10RoleAdminService\x12C\n" +
	"\n" +
	"AssignRole\x12\x19.idm.v1.AssignRoleRequest\x1a\x1a.idm.v1.AssignRoleResponse\x12C\n" +
	"\n" +
	"RevokeRole\x12\x19.idm.v1.RevokeRoleRequest\x1a\x1a.idm.v1.RevokeRoleResponse2\xbe\x03\n" +
	"\x0fIamAdminService\x12@\n" +
	"\tListRoles\x12\x18.idm.v1.ListRolesRequest\x1a\x19.idm.v1.ListRolesResponse\x12R\n" +
	"\x0fListPermissions\x12\x1e.idm.v1.ListPermissionsRequest\x1a\x1f.idm.v1.ListPermissionsResponse\x12[\n" +
	"\x12GetRolePermissions\x12!.idm.v1.GetRolePermissionsRequest\x1a\".idm.v1.GetRolePermissionsResponse\x12d\n" +
	"\x15ListSubjectsWithRoles\x12$.idm.v1.ListSubjectsWithRolesRequest\x1a%.idm.v1.ListSubjectsWithRolesResponse\x12R\n" +
	"\x0fGetSubjectRoles\x12\x1e.idm.v1.GetSubjectRolesRequest\x1a\x1f.idm.v1.GetSubjectRolesResponse2\xf9\x03\n" +
	"\x11IamCatalogService\x12C\n" +
	"\n" +
	"CreateRole\x12\x19.idm.v1.CreateRoleRequest\x1a\x1a.idm.v1.CreateRoleResponse\x12C\n" +
	"\n" +
	"DeleteRole\x12\x19.idm.v1.DeleteRoleRequest\x1a\x1a.idm.v1.DeleteRoleResponse\x12U\n" +
	"\x10CreatePermission\x12\x1f.idm.v1.CreatePermissionRequest\x1a .idm.v1.CreatePermissionResponse\x12U\n" +
	"\x10DeletePermission\x12\x1f.idm.v1.DeletePermissionRequest\x1a .idm.v1.DeletePermissionResponse\x12U\n" +
	"\x10AttachPermission\x12\x1f.idm.v1.AttachPermissionRequest\x1a .idm.v1.AttachPermissionResponse\x12U\n" +
	"\x10DetachPermission\x12\x1f.idm.v1.DetachPermissionRequest\x1a .idm.v1.DetachPermissionResponse2\xb6\x01\n" +
	"\x0fIdentityService\x12O\n" +
	"\x0eSearchSubjects\x12\x1d.idm.v1.SearchSubjectsRequest\x1a\x1e.idm.v1.SearchSubjectsResponse\x12R\n" +
	"\x0fResolveSubjects\x12\x1e.idm.v1.ResolveSubjectsRequest\x1a\x1f.idm.v1.ResolveSubjectsResponseB,Z*github.com/YuriB9/idp/pkg/api/idm/v1;idmv1b\x06proto3"

var (
	file_idm_v1_idm_proto_rawDescOnce sync.Once
	file_idm_v1_idm_proto_rawDescData []byte
)

func file_idm_v1_idm_proto_rawDescGZIP() []byte {
	file_idm_v1_idm_proto_rawDescOnce.Do(func() {
		file_idm_v1_idm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idm_v1_idm_proto_rawDesc), len(file_idm_v1_idm_proto_rawDesc)))
	})
	return file_idm_v1_idm_proto_rawDescData
}

var file_idm_v1_idm_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_idm_v1_idm_proto_goTypes = []any{
	(*SubjectIdentity)(nil),               // 0: idm.v1.SubjectIdentity
	(*SearchSubjectsRequest)(nil),         // 1: idm.v1.SearchSubjectsRequest
	(*SearchSubjectsResponse)(nil),        // 2: idm.v1.SearchSubjectsResponse
	(*ResolveSubjectsRequest)(nil),        // 3: idm.v1.ResolveSubjectsRequest
	(*ResolveSubjectsResponse)(nil),       // 4: idm.v1.ResolveSubjectsResponse
	(*Role)(nil),                          // 5: idm.v1.Role
	(*Permission)(nil),                    // 6: idm.v1.Permission
	(*SubjectRoles)(nil),                  // 7: idm.v1.SubjectRoles
	(*ListRolesRequest)(nil),              // 8: idm.v1.ListRolesRequest
	(*ListRolesResponse)(nil),             // 9: idm.v1.ListRolesResponse
	(*ListPermissionsRequest)(nil),        // 10: idm.v1.ListPermissionsRequest
	(*ListPermissionsResponse)(nil),       // 11: idm.v1.ListPermissionsResponse
	(*GetRolePermissionsRequest)(nil),     // 12: idm.v1.GetRolePermissionsRequest
	(*GetRolePermissionsResponse)(nil),    // 13: idm.v1.GetRolePermissionsResponse
	(*ListSubjectsWithRolesRequest)(nil),  // 14: idm.v1.ListSubjectsWithRolesRequest
	(*ListSubjectsWithRolesResponse)(nil), // 15: idm.v1.ListSubjectsWithRolesResponse
	(*GetSubjectRolesRequest)(nil),        // 16: idm.v1.GetSubjectRolesRequest
	(*GetSubjectRolesResponse)(nil),       // 17: idm.v1.GetSubjectRolesResponse
	(*CheckAccessRequest)(nil),            // 18: idm.v1.CheckAccessRequest
	(*CheckAccessResponse)(nil),           // 19: idm.v1.CheckAccessResponse
	(*AssignRoleRequest)(nil),             // 20: idm.v1.AssignRoleRequest
	(*AssignRoleResponse)(nil),            // 21: idm.v1.AssignRoleResponse
	(*RevokeRoleRequest)(nil),             // 22: idm.v1.RevokeRoleRequest
	(*RevokeRoleResponse)(nil),            // 23: idm.v1.RevokeRoleResponse
	(*RolePermissions)(nil),               // 24: idm.v1.RolePermissions
	(*CreateRoleRequest)(nil),             // 25: idm.v1.CreateRoleRequest
	(*CreateRoleResponse)(nil),            // 26: idm.v1.CreateRoleResponse
	(*DeleteRoleRequest)(nil),             // 27: idm.v1.DeleteRoleRequest
	(*DeleteRoleResponse)(nil),            // 28: idm.v1.DeleteRoleResponse
	(*CreatePermissionRequest)(nil),       // 29: idm.v1.CreatePermissionRequest
	(*CreatePermissionResponse)(nil),      // 30: idm.v1.CreatePermissionResponse
	(*DeletePermissionRequest)(nil),       // 31: idm.v1.DeletePermissionRequest
	(*DeletePermissionResponse)(nil),      // 32: idm.v1.DeletePermissionResponse
	(*AttachPermissionRequest)(nil),       // 33: idm.v1.AttachPermissionRequest
	(*AttachPermissionResponse)(nil),      // 34: idm.v1.AttachPermissionResponse
	(*DetachPermissionRequest)(nil),       // 35: idm.v1.DetachPermissionRequest
	(*DetachPermissionResponse)(nil),      // 36: idm.v1.DetachPermissionResponse
}
var file_idm_v1_idm_proto_depIdxs = []int32{
	0,  // 0: idm.v1.SearchSubjectsResponse.subjects:type_name -> idm.v1.SubjectIdentity
	0,  // 1: idm.v1.ResolveSubjectsResponse.subjects:type_name -> idm.v1.SubjectIdentity
	5,  // 2: idm.v1.ListRolesResponse.roles:type_name -> idm.v1.Role
	6,  // 3: idm.v1.ListPermissionsResponse.permissions:type_name -> idm.v1.Permission
	6,  // 4: idm.v1.GetRolePermissionsResponse.permissions:type_name -> idm.v1.Permission
	7,  // 5: idm.v1.ListSubjectsWithRolesResponse.subjects:type_name -> idm.v1.SubjectRoles
	6,  // 6: idm.v1.RolePermissions.permissions:type_name -> idm.v1.Permission
	5,  // 7: idm.v1.CreateRoleResponse.role:type_name -> idm.v1.Role
	6,  // 8: idm.v1.CreatePermissionResponse.permission:type_name -> idm.v1.Permission
	24, // 9: idm.v1.AttachPermissionResponse.role_permissions:type_name -> idm.v1.RolePermissions
	24, // 10: idm.v1.DetachPermissionResponse.role_permissions:type_name -> idm.v1.RolePermissions
	18, // 11: idm.v1.AccessService.CheckAccess:input_type -> idm.v1.CheckAccessRequest
	20, // 12: idm.v1.RoleAdminService.AssignRole:input_type -> idm.v1.AssignRoleRequest
	22, // 13: idm.v1.RoleAdminService.RevokeRole:input_type -> idm.v1.RevokeRoleRequest
	8,  // 14: idm.v1.IamAdminService.ListRoles:input_type -> idm.v1.ListRolesRequest
	10, // 15: idm.v1.IamAdminService.ListPermissions:input_type -> idm.v1.ListPermissionsRequest
	12, // 16: idm.v1.IamAdminService.GetRolePermissions:input_type -> idm.v1.GetRolePermissionsRequest
	14, // 17: idm.v1.IamAdminService.ListSubjectsWithRoles:input_type -> idm.v1.ListSubjectsWithRolesRequest
	16, // 18: idm.v1.IamAdminService.GetSubjectRoles:input_type -> idm.v1.GetSubjectRolesRequest
	25, // 19: idm.v1.IamCatalogService.CreateRole:input_type -> idm.v1.CreateRoleRequest
	27, // 20: idm.v1.IamCatalogService.DeleteRole:input_type -> idm.v1.DeleteRoleRequest
	29, // 21: idm.v1.IamCatalogService.CreatePermission:input_type -> idm.v1.CreatePermissionRequest
	31, // 22: idm.v1.IamCatalogService.DeletePermission:input_type -> idm.v1.DeletePermissionRequest
	33, // 23: idm.v1.IamCatalogService.AttachPermission:input_type -> idm.v1.AttachPermissionRequest
	35, // 24: idm.v1.IamCatalogService.DetachPermission:input_type -> idm.v1.DetachPermissionRequest
	1,  // 25: idm.v1.IdentityService.SearchSubjects:input_type -> idm.v1.SearchSubjectsRequest
	3,  // 26: idm.v1.IdentityService.ResolveSubjects:input_type -> idm.v1.ResolveSubjectsRequest
	19, // 27: idm.v1.AccessService.CheckAccess:output_type -> idm.v1.CheckAccessResponse
	21, // 28: idm.v1.RoleAdminService.AssignRole:output_type -> idm.v1.AssignRoleResponse
	23, // 29: idm.v1.RoleAdminService.RevokeRole:output_type -> idm.v1.RevokeRoleResponse
	9,  // 30: idm.v1.IamAdminService.ListRoles:output_type -> idm.v1.ListRolesResponse
	11, // 31: idm.v1.IamAdminService.ListPermissions:output_type -> idm.v1.ListPermissionsResponse
	13, // 32: idm.v1.IamAdminService.GetRolePermissions:output_type -> idm.v1.GetRolePermissionsResponse
	15, // 33: idm.v1.IamAdminService.ListSubjectsWithRoles:output_type -> idm.v1.ListSubjectsWithRolesResponse
	17, // 34: idm.v1.IamAdminService.GetSubjectRoles:output_type -> idm.v1.GetSubjectRolesResponse
	26, // 35: idm.v1.IamCatalogService.CreateRole:output_type -> idm.v1.CreateRoleResponse
	28, // 36: idm.v1.IamCatalogService.DeleteRole:output_type -> idm.v1.DeleteRoleResponse
	30, // 37: idm.v1.IamCatalogService.CreatePermission:output_type -> idm.v1.CreatePermissionResponse
	32, // 38: idm.v1.IamCatalogService.DeletePermission:output_type -> idm.v1.DeletePermissionResponse
	34, // 39: idm.v1.IamCatalogService.AttachPermission:output_type -> idm.v1.AttachPermissionResponse
	36, // 40: idm.v1.IamCatalogService.DetachPermission:output_type -> idm.v1.DetachPermissionResponse
	2,  // 41: idm.v1.IdentityService.SearchSubjects:output_type -> idm.v1.SearchSubjectsResponse
	4,  // 42: idm.v1.IdentityService.ResolveSubjects:output_type -> idm.v1.ResolveSubjectsResponse
	27, // [27:43] is the sub-list for method output_type
	11, // [11:27] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_idm_v1_idm_proto_init() }
func file_idm_v1_idm_proto_init() {
	if File_idm_v1_idm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idm_v1_idm_proto_rawDesc), len(file_idm_v1_idm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_idm_v1_idm_proto_goTypes,
		DependencyIndexes: file_idm_v1_idm_proto_depIdxs,
		MessageInfos:      file_idm_v1_idm_proto_msgTypes,
	}.Build()
	File_idm_v1_idm_proto = out.File
	file_idm_v1_idm_proto_goTypes = nil
	file_idm_v1_idm_proto_depIdxs = nil
}
