// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: idm/v1/idm.proto

// Пакет idm.v1 — контракт сервиса IDM (права/роли). Источник правды для
// внутренних вызовов gateway↔idm (ADR-0002). В MVP — минимальный RBAC через
// CheckAccess; интерфейс целевой, наполнение ролей — позже.

package idmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccessService_CheckAccess_FullMethodName = "/idm.v1.AccessService/CheckAccess"
)

// AccessServiceClient is the client API for AccessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AccessService отвечает на вопрос «можно ли субъекту выполнить действие над
// ресурсом».
type AccessServiceClient interface {
	// CheckAccess проверяет право субъекта на действие над ресурсом.
	CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*CheckAccessResponse, error)
}

type accessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessServiceClient(cc grpc.ClientConnInterface) AccessServiceClient {
	return &accessServiceClient{cc}
}

func (c *accessServiceClient) CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*CheckAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAccessResponse)
	err := c.cc.Invoke(ctx, AccessService_CheckAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessServiceServer is the server API for AccessService service.
// All implementations must embed UnimplementedAccessServiceServer
// for forward compatibility.
//
// AccessService отвечает на вопрос «можно ли субъекту выполнить действие над
// ресурсом».
type AccessServiceServer interface {
	// CheckAccess проверяет право субъекта на действие над ресурсом.
	CheckAccess(context.Context, *CheckAccessRequest) (*CheckAccessResponse, error)
	mustEmbedUnimplementedAccessServiceServer()
}

// UnimplementedAccessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccessServiceServer struct{}

func (UnimplementedAccessServiceServer) CheckAccess(context.Context, *CheckAccessRequest) (*CheckAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAccess not implemented")
}
func (UnimplementedAccessServiceServer) mustEmbedUnimplementedAccessServiceServer() {}
func (UnimplementedAccessServiceServer) testEmbeddedByValue()                       {}

// UnsafeAccessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessServiceServer will
// result in compilation errors.
type UnsafeAccessServiceServer interface {
	mustEmbedUnimplementedAccessServiceServer()
}

func RegisterAccessServiceServer(s grpc.ServiceRegistrar, srv AccessServiceServer) {
	// If the following call panics, it indicates UnimplementedAccessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccessService_ServiceDesc, srv)
}

func _AccessService_CheckAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).CheckAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_CheckAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).CheckAccess(ctx, req.(*CheckAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessService_ServiceDesc is the grpc.ServiceDesc for AccessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idm.v1.AccessService",
	HandlerType: (*AccessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAccess",
			Handler:    _AccessService_CheckAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idm/v1/idm.proto",
}

const (
	RoleAdminService_AssignRole_FullMethodName = "/idm.v1.RoleAdminService/AssignRole"
	RoleAdminService_RevokeRole_FullMethodName = "/idm.v1.RoleAdminService/RevokeRole"
)

// RoleAdminServiceClient is the client API for RoleAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RoleAdminService — управляющий контракт ролей: программная выдача/отзыв роли
// субъекту для синхронизации из доменных потоков (например, «Изменение
// владельцев»). После изменения привязок IDM инвалидирует кэш решений по
// затронутому субъекту. Путь не публичный (не периметр); вызывается доменными
// сервисами/worker'ом. BREAKING: добавление сервиса в существующий контракт idm.
type RoleAdminServiceClient interface {
	// AssignRole выдаёт субъекту роль (идемпотентно: повторная выдача — успех).
	// Несуществующая роль → NotFound; пустые поля → InvalidArgument.
	AssignRole(ctx context.Context, in *AssignRoleRequest, opts ...grpc.CallOption) (*AssignRoleResponse, error)
	// RevokeRole отзывает у субъекта роль (идемпотентно: отзыв отсутствующей — успех).
	// Пустые поля → InvalidArgument.
	RevokeRole(ctx context.Context, in *RevokeRoleRequest, opts ...grpc.CallOption) (*RevokeRoleResponse, error)
}

type roleAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoleAdminServiceClient(cc grpc.ClientConnInterface) RoleAdminServiceClient {
	return &roleAdminServiceClient{cc}
}

func (c *roleAdminServiceClient) AssignRole(ctx context.Context, in *AssignRoleRequest, opts ...grpc.CallOption) (*AssignRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignRoleResponse)
	err := c.cc.Invoke(ctx, RoleAdminService_AssignRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleAdminServiceClient) RevokeRole(ctx context.Context, in *RevokeRoleRequest, opts ...grpc.CallOption) (*RevokeRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeRoleResponse)
	err := c.cc.Invoke(ctx, RoleAdminService_RevokeRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoleAdminServiceServer is the server API for RoleAdminService service.
// All implementations must embed UnimplementedRoleAdminServiceServer
// for forward compatibility.
//
// RoleAdminService — управляющий контракт ролей: программная выдача/отзыв роли
// субъекту для синхронизации из доменных потоков (например, «Изменение
// владельцев»). После изменения привязок IDM инвалидирует кэш решений по
// затронутому субъекту. Путь не публичный (не периметр); вызывается доменными
// сервисами/worker'ом. BREAKING: добавление сервиса в существующий контракт idm.
type RoleAdminServiceServer interface {
	// AssignRole выдаёт субъекту роль (идемпотентно: повторная выдача — успех).
	// Несуществующая роль → NotFound; пустые поля → InvalidArgument.
	AssignRole(context.Context, *AssignRoleRequest) (*AssignRoleResponse, error)
	// RevokeRole отзывает у субъекта роль (идемпотентно: отзыв отсутствующей — успех).
	// Пустые поля → InvalidArgument.
	RevokeRole(context.Context, *RevokeRoleRequest) (*RevokeRoleResponse, error)
	mustEmbedUnimplementedRoleAdminServiceServer()
}

// UnimplementedRoleAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoleAdminServiceServer struct{}

func (UnimplementedRoleAdminServiceServer) AssignRole(context.Context, *AssignRoleRequest) (*AssignRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignRole not implemented")
}
func (UnimplementedRoleAdminServiceServer) RevokeRole(context.Context, *RevokeRoleRequest) (*RevokeRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeRole not implemented")
}
func (UnimplementedRoleAdminServiceServer) mustEmbedUnimplementedRoleAdminServiceServer() {}
func (UnimplementedRoleAdminServiceServer) testEmbeddedByValue()                          {}

// UnsafeRoleAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoleAdminServiceServer will
// result in compilation errors.
type UnsafeRoleAdminServiceServer interface {
	mustEmbedUnimplementedRoleAdminServiceServer()
}

func RegisterRoleAdminServiceServer(s grpc.ServiceRegistrar, srv RoleAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedRoleAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoleAdminService_ServiceDesc, srv)
}

func _RoleAdminService_AssignRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleAdminServiceServer).AssignRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleAdminService_AssignRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleAdminServiceServer).AssignRole(ctx, req.(*AssignRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleAdminService_RevokeRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleAdminServiceServer).RevokeRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleAdminService_RevokeRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleAdminServiceServer).RevokeRole(ctx, req.(*RevokeRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoleAdminService_ServiceDesc is the grpc.ServiceDesc for RoleAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoleAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idm.v1.RoleAdminService",
	HandlerType: (*RoleAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignRole",
			Handler:    _RoleAdminService_AssignRole_Handler,
		},
		{
			MethodName: "RevokeRole",
			Handler:    _RoleAdminService_RevokeRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idm/v1/idm.proto",
}

const (
	IamAdminService_ListRoles_FullMethodName             = "/idm.v1.IamAdminService/ListRoles"
	IamAdminService_ListPermissions_FullMethodName       = "/idm.v1.IamAdminService/ListPermissions"
	IamAdminService_GetRolePermissions_FullMethodName    = "/idm.v1.IamAdminService/GetRolePermissions"
	IamAdminService_ListSubjectsWithRoles_FullMethodName = "/idm.v1.IamAdminService/ListSubjectsWithRoles"
	IamAdminService_GetSubjectRoles_FullMethodName       = "/idm.v1.IamAdminService/GetSubjectRoles"
)

// IamAdminServiceClient is the client API for IamAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IamAdminService — читающий контракт IAM-админки (ADR-0014): просмотр каталога
// ролей/прав и привязок субъект↔роль. Только чтение (без побочных эффектов на
// кэш решений). Путь привилегированный: gateway проверяет право (read,
// iam:global) перед КАЖДОЙ ручкой (fail-closed). Расширение аддитивно
// (wire-совместимо): новый сервис и сообщения, существующие RPC не меняются.
// Мутации привязок выполняет RoleAdminService (переиспользуется, не дублируется).
type IamAdminServiceClient interface {
	// ListRoles возвращает все роли каталога (без пагинации — справочник мал).
	ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error)
	// ListPermissions возвращает все права каталога (без пагинации).
	ListPermissions(ctx context.Context, in *ListPermissionsRequest, opts ...grpc.CallOption) (*ListPermissionsResponse, error)
	// GetRolePermissions возвращает права конкретной роли. Несуществующая роль →
	// NotFound; пустое имя → InvalidArgument.
	GetRolePermissions(ctx context.Context, in *GetRolePermissionsRequest, opts ...grpc.CallOption) (*GetRolePermissionsResponse, error)
	// ListSubjectsWithRoles перечисляет субъектов (DISTINCT subject из
	// subject_roles) с их ролями; keyset-пагинация по subject (ASC). Субъекты без
	// ролей системе неизвестны и не возвращаются.
	ListSubjectsWithRoles(ctx context.Context, in *ListSubjectsWithRolesRequest, opts ...grpc.CallOption) (*ListSubjectsWithRolesResponse, error)
	// GetSubjectRoles возвращает роли субъекта (пустой набор, не NotFound, если
	// ролей нет); пустой subject → InvalidArgument.
	GetSubjectRoles(ctx context.Context, in *GetSubjectRolesRequest, opts ...grpc.CallOption) (*GetSubjectRolesResponse, error)
}

type iamAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIamAdminServiceClient(cc grpc.ClientConnInterface) IamAdminServiceClient {
	return &iamAdminServiceClient{cc}
}

func (c *iamAdminServiceClient) ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRolesResponse)
	err := c.cc.Invoke(ctx, IamAdminService_ListRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamAdminServiceClient) ListPermissions(ctx context.Context, in *ListPermissionsRequest, opts ...grpc.CallOption) (*ListPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPermissionsResponse)
	err := c.cc.Invoke(ctx, IamAdminService_ListPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamAdminServiceClient) GetRolePermissions(ctx context.Context, in *GetRolePermissionsRequest, opts ...grpc.CallOption) (*GetRolePermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRolePermissionsResponse)
	err := c.cc.Invoke(ctx, IamAdminService_GetRolePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamAdminServiceClient) ListSubjectsWithRoles(ctx context.Context, in *ListSubjectsWithRolesRequest, opts ...grpc.CallOption) (*ListSubjectsWithRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSubjectsWithRolesResponse)
	err := c.cc.Invoke(ctx, IamAdminService_ListSubjectsWithRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamAdminServiceClient) GetSubjectRoles(ctx context.Context, in *GetSubjectRolesRequest, opts ...grpc.CallOption) (*GetSubjectRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubjectRolesResponse)
	err := c.cc.Invoke(ctx, IamAdminService_GetSubjectRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IamAdminServiceServer is the server API for IamAdminService service.
// All implementations must embed UnimplementedIamAdminServiceServer
// for forward compatibility.
//
// IamAdminService — читающий контракт IAM-админки (ADR-0014): просмотр каталога
// ролей/прав и привязок субъект↔роль. Только чтение (без побочных эффектов на
// кэш решений). Путь привилегированный: gateway проверяет право (read,
// iam:global) перед КАЖДОЙ ручкой (fail-closed). Расширение аддитивно
// (wire-совместимо): новый сервис и сообщения, существующие RPC не меняются.
// Мутации привязок выполняет RoleAdminService (переиспользуется, не дублируется).
type IamAdminServiceServer interface {
	// ListRoles возвращает все роли каталога (без пагинации — справочник мал).
	ListRoles(context.Context, *ListRolesRequest) (*ListRolesResponse, error)
	// ListPermissions возвращает все права каталога (без пагинации).
	ListPermissions(context.Context, *ListPermissionsRequest) (*ListPermissionsResponse, error)
	// GetRolePermissions возвращает права конкретной роли. Несуществующая роль →
	// NotFound; пустое имя → InvalidArgument.
	GetRolePermissions(context.Context, *GetRolePermissionsRequest) (*GetRolePermissionsResponse, error)
	// ListSubjectsWithRoles перечисляет субъектов (DISTINCT subject из
	// subject_roles) с их ролями; keyset-пагинация по subject (ASC). Субъекты без
	// ролей системе неизвестны и не возвращаются.
	ListSubjectsWithRoles(context.Context, *ListSubjectsWithRolesRequest) (*ListSubjectsWithRolesResponse, error)
	// GetSubjectRoles возвращает роли субъекта (пустой набор, не NotFound, если
	// ролей нет); пустой subject → InvalidArgument.
	GetSubjectRoles(context.Context, *GetSubjectRolesRequest) (*GetSubjectRolesResponse, error)
	mustEmbedUnimplementedIamAdminServiceServer()
}

// UnimplementedIamAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIamAdminServiceServer struct{}

func (UnimplementedIamAdminServiceServer) ListRoles(context.Context, *ListRolesRequest) (*ListRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoles not implemented")
}
func (UnimplementedIamAdminServiceServer) ListPermissions(context.Context, *ListPermissionsRequest) (*ListPermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPermissions not implemented")
}
func (UnimplementedIamAdminServiceServer) GetRolePermissions(context.Context, *GetRolePermissionsRequest) (*GetRolePermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRolePermissions not implemented")
}
func (UnimplementedIamAdminServiceServer) ListSubjectsWithRoles(context.Context, *ListSubjectsWithRolesRequest) (*ListSubjectsWithRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSubjectsWithRoles not implemented")
}
func (UnimplementedIamAdminServiceServer) GetSubjectRoles(context.Context, *GetSubjectRolesRequest) (*GetSubjectRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubjectRoles not implemented")
}
func (UnimplementedIamAdminServiceServer) mustEmbedUnimplementedIamAdminServiceServer() {}
func (UnimplementedIamAdminServiceServer) testEmbeddedByValue()                         {}

// UnsafeIamAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IamAdminServiceServer will
// result in compilation errors.
type UnsafeIamAdminServiceServer interface {
	mustEmbedUnimplementedIamAdminServiceServer()
}

func RegisterIamAdminServiceServer(s grpc.ServiceRegistrar, srv IamAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedIamAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IamAdminService_ServiceDesc, srv)
}

func _IamAdminService_ListRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamAdminServiceServer).ListRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamAdminService_ListRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamAdminServiceServer).ListRoles(ctx, req.(*ListRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamAdminService_ListPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamAdminServiceServer).ListPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamAdminService_ListPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamAdminServiceServer).ListPermissions(ctx, req.(*ListPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamAdminService_GetRolePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolePermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamAdminServiceServer).GetRolePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamAdminService_GetRolePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamAdminServiceServer).GetRolePermissions(ctx, req.(*GetRolePermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamAdminService_ListSubjectsWithRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubjectsWithRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamAdminServiceServer).ListSubjectsWithRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamAdminService_ListSubjectsWithRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamAdminServiceServer).ListSubjectsWithRoles(ctx, req.(*ListSubjectsWithRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamAdminService_GetSubjectRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubjectRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamAdminServiceServer).GetSubjectRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamAdminService_GetSubjectRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamAdminServiceServer).GetSubjectRoles(ctx, req.(*GetSubjectRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IamAdminService_ServiceDesc is the grpc.ServiceDesc for IamAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IamAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idm.v1.IamAdminService",
	HandlerType: (*IamAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRoles",
			Handler:    _IamAdminService_ListRoles_Handler,
		},
		{
			MethodName: "ListPermissions",
			Handler:    _IamAdminService_ListPermissions_Handler,
		},
		{
			MethodName: "GetRolePermissions",
			Handler:    _IamAdminService_GetRolePermissions_Handler,
		},
		{
			MethodName: "ListSubjectsWithRoles",
			Handler:    _IamAdminService_ListSubjectsWithRoles_Handler,
		},
		{
			MethodName: "GetSubjectRoles",
			Handler:    _IamAdminService_GetSubjectRoles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idm/v1/idm.proto",
}

const (
	IamCatalogService_CreateRole_FullMethodName       = "/idm.v1.IamCatalogService/CreateRole"
	IamCatalogService_DeleteRole_FullMethodName       = "/idm.v1.IamCatalogService/DeleteRole"
	IamCatalogService_CreatePermission_FullMethodName = "/idm.v1.IamCatalogService/CreatePermission"
	IamCatalogService_DeletePermission_FullMethodName = "/idm.v1.IamCatalogService/DeletePermission"
	IamCatalogService_AttachPermission_FullMethodName = "/idm.v1.IamCatalogService/AttachPermission"
	IamCatalogService_DetachPermission_FullMethodName = "/idm.v1.IamCatalogService/DetachPermission"
)

// IamCatalogServiceClient is the client API for IamCatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IamCatalogService — мутирующий контракт каталога IAM (ADR-0015): структурные
// изменения самого каталога ролей/прав — создание/удаление ролей и прав,
// правка набора прав роли (attach/detach). Путь привилегированный: gateway
// проверяет право (manage, iam:global) перед КАЖДОЙ ручкой (fail-closed),
// отдельно и привилегированнее, чем write (assign/revoke). Любая структурная
// мутация → ШИРОКАЯ инвалидация кэша решений (поколение idm:cache:gen), т.к.
// правка role_permissions/удаление роли затрагивает ВСЕХ носителей роли.
// Системные (сидированные) роли/права защищены от удаления и правки набора прав
// (FailedPrecondition). Расширение аддитивно (wire-совместимо): новый сервис и
// сообщения, существующие RPC не меняются. Мутации привязок субъект↔роль
// выполняет RoleAdminService (переиспользуется, не дублируется).
type IamCatalogServiceClient interface {
	// CreateRole создаёт пользовательскую роль (system=false). Дубль имени →
	// AlreadyExists (не идемпотентно); пустое имя → InvalidArgument.
	CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error)
	// DeleteRole удаляет роль (каскад subject_roles/role_permissions). Системная
	// роль → FailedPrecondition; несуществующая → NotFound.
	DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*DeleteRoleResponse, error)
	// CreatePermission создаёт пользовательское право (system=false). Дубль пары
	// (action, resource) → AlreadyExists; пустые поля → InvalidArgument.
	CreatePermission(ctx context.Context, in *CreatePermissionRequest, opts ...grpc.CallOption) (*CreatePermissionResponse, error)
	// DeletePermission удаляет право (каскад role_permissions). Системное право →
	// FailedPrecondition; несуществующее → NotFound.
	DeletePermission(ctx context.Context, in *DeletePermissionRequest, opts ...grpc.CallOption) (*DeletePermissionResponse, error)
	// AttachPermission прикрепляет право к роли (идемпотентно: повтор — успех).
	// Роль/право не найдены → NotFound; системная роль → FailedPrecondition.
	// Возвращает актуальный набор прав роли.
	AttachPermission(ctx context.Context, in *AttachPermissionRequest, opts ...grpc.CallOption) (*AttachPermissionResponse, error)
	// DetachPermission открепляет право от роли (идемпотентно: открепление
	// непривязанного — успех). Роль не найдена → NotFound; системная роль →
	// FailedPrecondition. Возвращает актуальный набор прав роли.
	DetachPermission(ctx context.Context, in *DetachPermissionRequest, opts ...grpc.CallOption) (*DetachPermissionResponse, error)
}

type iamCatalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIamCatalogServiceClient(cc grpc.ClientConnInterface) IamCatalogServiceClient {
	return &iamCatalogServiceClient{cc}
}

func (c *iamCatalogServiceClient) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*CreateRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRoleResponse)
	err := c.cc.Invoke(ctx, IamCatalogService_CreateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamCatalogServiceClient) DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*DeleteRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRoleResponse)
	err := c.cc.Invoke(ctx, IamCatalogService_DeleteRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamCatalogServiceClient) CreatePermission(ctx context.Context, in *CreatePermissionRequest, opts ...grpc.CallOption) (*CreatePermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePermissionResponse)
	err := c.cc.Invoke(ctx, IamCatalogService_CreatePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamCatalogServiceClient) DeletePermission(ctx context.Context, in *DeletePermissionRequest, opts ...grpc.CallOption) (*DeletePermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePermissionResponse)
	err := c.cc.Invoke(ctx, IamCatalogService_DeletePermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamCatalogServiceClient) AttachPermission(ctx context.Context, in *AttachPermissionRequest, opts ...grpc.CallOption) (*AttachPermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachPermissionResponse)
	err := c.cc.Invoke(ctx, IamCatalogService_AttachPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamCatalogServiceClient) DetachPermission(ctx context.Context, in *DetachPermissionRequest, opts ...grpc.CallOption) (*DetachPermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetachPermissionResponse)
	err := c.cc.Invoke(ctx, IamCatalogService_DetachPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IamCatalogServiceServer is the server API for IamCatalogService service.
// All implementations must embed UnimplementedIamCatalogServiceServer
// for forward compatibility.
//
// IamCatalogService — мутирующий контракт каталога IAM (ADR-0015): структурные
// изменения самого каталога ролей/прав — создание/удаление ролей и прав,
// правка набора прав роли (attach/detach). Путь привилегированный: gateway
// проверяет право (manage, iam:global) перед КАЖДОЙ ручкой (fail-closed),
// отдельно и привилегированнее, чем write (assign/revoke). Любая структурная
// мутация → ШИРОКАЯ инвалидация кэша решений (поколение idm:cache:gen), т.к.
// правка role_permissions/удаление роли затрагивает ВСЕХ носителей роли.
// Системные (сидированные) роли/права защищены от удаления и правки набора прав
// (FailedPrecondition). Расширение аддитивно (wire-совместимо): новый сервис и
// сообщения, существующие RPC не меняются. Мутации привязок субъект↔роль
// выполняет RoleAdminService (переиспользуется, не дублируется).
type IamCatalogServiceServer interface {
	// CreateRole создаёт пользовательскую роль (system=false). Дубль имени →
	// AlreadyExists (не идемпотентно); пустое имя → InvalidArgument.
	CreateRole(context.Context, *CreateRoleRequest) (*CreateRoleResponse, error)
	// DeleteRole удаляет роль (каскад subject_roles/role_permissions). Системная
	// роль → FailedPrecondition; несуществующая → NotFound.
	DeleteRole(context.Context, *DeleteRoleRequest) (*DeleteRoleResponse, error)
	// CreatePermission создаёт пользовательское право (system=false). Дубль пары
	// (action, resource) → AlreadyExists; пустые поля → InvalidArgument.
	CreatePermission(context.Context, *CreatePermissionRequest) (*CreatePermissionResponse, error)
	// DeletePermission удаляет право (каскад role_permissions). Системное право →
	// FailedPrecondition; несуществующее → NotFound.
	DeletePermission(context.Context, *DeletePermissionRequest) (*DeletePermissionResponse, error)
	// AttachPermission прикрепляет право к роли (идемпотентно: повтор — успех).
	// Роль/право не найдены → NotFound; системная роль → FailedPrecondition.
	// Возвращает актуальный набор прав роли.
	AttachPermission(context.Context, *AttachPermissionRequest) (*AttachPermissionResponse, error)
	// DetachPermission открепляет право от роли (идемпотентно: открепление
	// непривязанного — успех). Роль не найдена → NotFound; системная роль →
	// FailedPrecondition. Возвращает актуальный набор прав роли.
	DetachPermission(context.Context, *DetachPermissionRequest) (*DetachPermissionResponse, error)
	mustEmbedUnimplementedIamCatalogServiceServer()
}

// UnimplementedIamCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIamCatalogServiceServer struct{}

func (UnimplementedIamCatalogServiceServer) CreateRole(context.Context, *CreateRoleRequest) (*CreateRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRole not implemented")
}
func (UnimplementedIamCatalogServiceServer) DeleteRole(context.Context, *DeleteRoleRequest) (*DeleteRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRole not implemented")
}
func (UnimplementedIamCatalogServiceServer) CreatePermission(context.Context, *CreatePermissionRequest) (*CreatePermissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePermission not implemented")
}
func (UnimplementedIamCatalogServiceServer) DeletePermission(context.Context, *DeletePermissionRequest) (*DeletePermissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePermission not implemented")
}
func (UnimplementedIamCatalogServiceServer) AttachPermission(context.Context, *AttachPermissionRequest) (*AttachPermissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachPermission not implemented")
}
func (UnimplementedIamCatalogServiceServer) DetachPermission(context.Context, *DetachPermissionRequest) (*DetachPermissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetachPermission not implemented")
}
func (UnimplementedIamCatalogServiceServer) mustEmbedUnimplementedIamCatalogServiceServer() {}
func (UnimplementedIamCatalogServiceServer) testEmbeddedByValue()                           {}

// UnsafeIamCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IamCatalogServiceServer will
// result in compilation errors.
type UnsafeIamCatalogServiceServer interface {
	mustEmbedUnimplementedIamCatalogServiceServer()
}

func RegisterIamCatalogServiceServer(s grpc.ServiceRegistrar, srv IamCatalogServiceServer) {
	// If the following call panics, it indicates UnimplementedIamCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IamCatalogService_ServiceDesc, srv)
}

func _IamCatalogService_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamCatalogServiceServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamCatalogService_CreateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamCatalogServiceServer).CreateRole(ctx, req.(*CreateRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamCatalogService_DeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamCatalogServiceServer).DeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamCatalogService_DeleteRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamCatalogServiceServer).DeleteRole(ctx, req.(*DeleteRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamCatalogService_CreatePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamCatalogServiceServer).CreatePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamCatalogService_CreatePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamCatalogServiceServer).CreatePermission(ctx, req.(*CreatePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamCatalogService_DeletePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamCatalogServiceServer).DeletePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamCatalogService_DeletePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamCatalogServiceServer).DeletePermission(ctx, req.(*DeletePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamCatalogService_AttachPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamCatalogServiceServer).AttachPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamCatalogService_AttachPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamCatalogServiceServer).AttachPermission(ctx, req.(*AttachPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamCatalogService_DetachPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamCatalogServiceServer).DetachPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamCatalogService_DetachPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamCatalogServiceServer).DetachPermission(ctx, req.(*DetachPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IamCatalogService_ServiceDesc is the grpc.ServiceDesc for IamCatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IamCatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idm.v1.IamCatalogService",
	HandlerType: (*IamCatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRole",
			Handler:    _IamCatalogService_CreateRole_Handler,
		},
		{
			MethodName: "DeleteRole",
			Handler:    _IamCatalogService_DeleteRole_Handler,
		},
		{
			MethodName: "CreatePermission",
			Handler:    _IamCatalogService_CreatePermission_Handler,
		},
		{
			MethodName: "DeletePermission",
			Handler:    _IamCatalogService_DeletePermission_Handler,
		},
		{
			MethodName: "AttachPermission",
			Handler:    _IamCatalogService_AttachPermission_Handler,
		},
		{
			MethodName: "DetachPermission",
			Handler:    _IamCatalogService_DetachPermission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idm/v1/idm.proto",
}

const (
	IdentityService_SearchSubjects_FullMethodName  = "/idm.v1.IdentityService/SearchSubjects"
	IdentityService_ResolveSubjects_FullMethodName = "/idm.v1.IdentityService/ResolveSubjects"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IdentityService — читающий контракт справочника субъектов из каталога
// идентичностей (OIDC/Keycloak, ADR-0016). Резолвит канонический ключ субъекта
// (sub из JWT, он же subject_roles.subject) в человекочитаемую идентичность
// (username/email/display name) и ищет пользователей realm для пикера назначения
// роли. Источник правды — живой запрос в Keycloak Admin REST + кэш с TTL
// (ОТДЕЛЬНЫЙ от кэша решений RBAC). Путь привилегированный: gateway проверяет
// право (read, iam:directory) перед КАЖДОЙ ручкой (fail-closed). Справочник НЕ
// критичен для CheckAccess (решение по sub не зависит от имён): при недоступном
// Keycloak ручки деградируют (Unavailable), управление ролями по сырому subject
// не ломается. Расширение аддитивно (wire-совместимо): новый сервис и сообщения,
// существующие RPC не меняются.
type IdentityServiceClient interface {
	// SearchSubjects ищет пользователей каталога по строке (username/email/имя) с
	// постраничной выдачей. Пустой/слишком короткий query или превышение лимита
	// page_size → InvalidArgument; недоступность Keycloak → Unavailable.
	SearchSubjects(ctx context.Context, in *SearchSubjectsRequest, opts ...grpc.CallOption) (*SearchSubjectsResponse, error)
	// ResolveSubjects резолвит набор канонических ключей (sub) в идентичности
	// (батч). Отсутствующий в каталоге субъект возвращается с found=false (не
	// опускается) — «осиротевший». Пустой список → InvalidArgument; недоступность
	// Keycloak → Unavailable.
	ResolveSubjects(ctx context.Context, in *ResolveSubjectsRequest, opts ...grpc.CallOption) (*ResolveSubjectsResponse, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) SearchSubjects(ctx context.Context, in *SearchSubjectsRequest, opts ...grpc.CallOption) (*SearchSubjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchSubjectsResponse)
	err := c.cc.Invoke(ctx, IdentityService_SearchSubjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) ResolveSubjects(ctx context.Context, in *ResolveSubjectsRequest, opts ...grpc.CallOption) (*ResolveSubjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveSubjectsResponse)
	err := c.cc.Invoke(ctx, IdentityService_ResolveSubjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations must embed UnimplementedIdentityServiceServer
// for forward compatibility.
//
// IdentityService — читающий контракт справочника субъектов из каталога
// идентичностей (OIDC/Keycloak, ADR-0016). Резолвит канонический ключ субъекта
// (sub из JWT, он же subject_roles.subject) в человекочитаемую идентичность
// (username/email/display name) и ищет пользователей realm для пикера назначения
// роли. Источник правды — живой запрос в Keycloak Admin REST + кэш с TTL
// (ОТДЕЛЬНЫЙ от кэша решений RBAC). Путь привилегированный: gateway проверяет
// право (read, iam:directory) перед КАЖДОЙ ручкой (fail-closed). Справочник НЕ
// критичен для CheckAccess (решение по sub не зависит от имён): при недоступном
// Keycloak ручки деградируют (Unavailable), управление ролями по сырому subject
// не ломается. Расширение аддитивно (wire-совместимо): новый сервис и сообщения,
// существующие RPC не меняются.
type IdentityServiceServer interface {
	// SearchSubjects ищет пользователей каталога по строке (username/email/имя) с
	// постраничной выдачей. Пустой/слишком короткий query или превышение лимита
	// page_size → InvalidArgument; недоступность Keycloak → Unavailable.
	SearchSubjects(context.Context, *SearchSubjectsRequest) (*SearchSubjectsResponse, error)
	// ResolveSubjects резолвит набор канонических ключей (sub) в идентичности
	// (батч). Отсутствующий в каталоге субъект возвращается с found=false (не
	// опускается) — «осиротевший». Пустой список → InvalidArgument; недоступность
	// Keycloak → Unavailable.
	ResolveSubjects(context.Context, *ResolveSubjectsRequest) (*ResolveSubjectsResponse, error)
	mustEmbedUnimplementedIdentityServiceServer()
}

// UnimplementedIdentityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServiceServer struct{}

func (UnimplementedIdentityServiceServer) SearchSubjects(context.Context, *SearchSubjectsRequest) (*SearchSubjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchSubjects not implemented")
}
func (UnimplementedIdentityServiceServer) ResolveSubjects(context.Context, *ResolveSubjectsRequest) (*ResolveSubjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveSubjects not implemented")
}
func (UnimplementedIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {}
func (UnimplementedIdentityServiceServer) testEmbeddedByValue()                         {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_SearchSubjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchSubjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).SearchSubjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_SearchSubjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).SearchSubjects(ctx, req.(*SearchSubjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_ResolveSubjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveSubjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ResolveSubjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ResolveSubjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ResolveSubjects(ctx, req.(*ResolveSubjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idm.v1.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchSubjects",
			Handler:    _IdentityService_SearchSubjects_Handler,
		},
		{
			MethodName: "ResolveSubjects",
			Handler:    _IdentityService_ResolveSubjects_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idm/v1/idm.proto",
}
