// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: idm/v1/idm.proto

// Пакет idm.v1 — контракт сервиса IDM (права/роли). Источник правды для
// внутренних вызовов gateway↔idm (ADR-0002). В MVP — минимальный RBAC через
// CheckAccess; интерфейс целевой, наполнение ролей — позже.

package idmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccessService_CheckAccess_FullMethodName = "/idm.v1.AccessService/CheckAccess"
)

// AccessServiceClient is the client API for AccessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AccessService отвечает на вопрос «можно ли субъекту выполнить действие над
// ресурсом».
type AccessServiceClient interface {
	// CheckAccess проверяет право субъекта на действие над ресурсом.
	CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*CheckAccessResponse, error)
}

type accessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessServiceClient(cc grpc.ClientConnInterface) AccessServiceClient {
	return &accessServiceClient{cc}
}

func (c *accessServiceClient) CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*CheckAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAccessResponse)
	err := c.cc.Invoke(ctx, AccessService_CheckAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessServiceServer is the server API for AccessService service.
// All implementations must embed UnimplementedAccessServiceServer
// for forward compatibility.
//
// AccessService отвечает на вопрос «можно ли субъекту выполнить действие над
// ресурсом».
type AccessServiceServer interface {
	// CheckAccess проверяет право субъекта на действие над ресурсом.
	CheckAccess(context.Context, *CheckAccessRequest) (*CheckAccessResponse, error)
	mustEmbedUnimplementedAccessServiceServer()
}

// UnimplementedAccessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccessServiceServer struct{}

func (UnimplementedAccessServiceServer) CheckAccess(context.Context, *CheckAccessRequest) (*CheckAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAccess not implemented")
}
func (UnimplementedAccessServiceServer) mustEmbedUnimplementedAccessServiceServer() {}
func (UnimplementedAccessServiceServer) testEmbeddedByValue()                       {}

// UnsafeAccessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessServiceServer will
// result in compilation errors.
type UnsafeAccessServiceServer interface {
	mustEmbedUnimplementedAccessServiceServer()
}

func RegisterAccessServiceServer(s grpc.ServiceRegistrar, srv AccessServiceServer) {
	// If the following call panics, it indicates UnimplementedAccessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccessService_ServiceDesc, srv)
}

func _AccessService_CheckAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).CheckAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_CheckAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).CheckAccess(ctx, req.(*CheckAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessService_ServiceDesc is the grpc.ServiceDesc for AccessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idm.v1.AccessService",
	HandlerType: (*AccessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAccess",
			Handler:    _AccessService_CheckAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idm/v1/idm.proto",
}

const (
	RoleAdminService_AssignRole_FullMethodName = "/idm.v1.RoleAdminService/AssignRole"
	RoleAdminService_RevokeRole_FullMethodName = "/idm.v1.RoleAdminService/RevokeRole"
)

// RoleAdminServiceClient is the client API for RoleAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RoleAdminService — управляющий контракт ролей: программная выдача/отзыв роли
// субъекту для синхронизации из доменных потоков (например, «Изменение
// владельцев»). После изменения привязок IDM инвалидирует кэш решений по
// затронутому субъекту. Путь не публичный (не периметр); вызывается доменными
// сервисами/worker'ом. BREAKING: добавление сервиса в существующий контракт idm.
type RoleAdminServiceClient interface {
	// AssignRole выдаёт субъекту роль (идемпотентно: повторная выдача — успех).
	// Несуществующая роль → NotFound; пустые поля → InvalidArgument.
	AssignRole(ctx context.Context, in *AssignRoleRequest, opts ...grpc.CallOption) (*AssignRoleResponse, error)
	// RevokeRole отзывает у субъекта роль (идемпотентно: отзыв отсутствующей — успех).
	// Пустые поля → InvalidArgument.
	RevokeRole(ctx context.Context, in *RevokeRoleRequest, opts ...grpc.CallOption) (*RevokeRoleResponse, error)
}

type roleAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoleAdminServiceClient(cc grpc.ClientConnInterface) RoleAdminServiceClient {
	return &roleAdminServiceClient{cc}
}

func (c *roleAdminServiceClient) AssignRole(ctx context.Context, in *AssignRoleRequest, opts ...grpc.CallOption) (*AssignRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignRoleResponse)
	err := c.cc.Invoke(ctx, RoleAdminService_AssignRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleAdminServiceClient) RevokeRole(ctx context.Context, in *RevokeRoleRequest, opts ...grpc.CallOption) (*RevokeRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeRoleResponse)
	err := c.cc.Invoke(ctx, RoleAdminService_RevokeRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoleAdminServiceServer is the server API for RoleAdminService service.
// All implementations must embed UnimplementedRoleAdminServiceServer
// for forward compatibility.
//
// RoleAdminService — управляющий контракт ролей: программная выдача/отзыв роли
// субъекту для синхронизации из доменных потоков (например, «Изменение
// владельцев»). После изменения привязок IDM инвалидирует кэш решений по
// затронутому субъекту. Путь не публичный (не периметр); вызывается доменными
// сервисами/worker'ом. BREAKING: добавление сервиса в существующий контракт idm.
type RoleAdminServiceServer interface {
	// AssignRole выдаёт субъекту роль (идемпотентно: повторная выдача — успех).
	// Несуществующая роль → NotFound; пустые поля → InvalidArgument.
	AssignRole(context.Context, *AssignRoleRequest) (*AssignRoleResponse, error)
	// RevokeRole отзывает у субъекта роль (идемпотентно: отзыв отсутствующей — успех).
	// Пустые поля → InvalidArgument.
	RevokeRole(context.Context, *RevokeRoleRequest) (*RevokeRoleResponse, error)
	mustEmbedUnimplementedRoleAdminServiceServer()
}

// UnimplementedRoleAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoleAdminServiceServer struct{}

func (UnimplementedRoleAdminServiceServer) AssignRole(context.Context, *AssignRoleRequest) (*AssignRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignRole not implemented")
}
func (UnimplementedRoleAdminServiceServer) RevokeRole(context.Context, *RevokeRoleRequest) (*RevokeRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeRole not implemented")
}
func (UnimplementedRoleAdminServiceServer) mustEmbedUnimplementedRoleAdminServiceServer() {}
func (UnimplementedRoleAdminServiceServer) testEmbeddedByValue()                          {}

// UnsafeRoleAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoleAdminServiceServer will
// result in compilation errors.
type UnsafeRoleAdminServiceServer interface {
	mustEmbedUnimplementedRoleAdminServiceServer()
}

func RegisterRoleAdminServiceServer(s grpc.ServiceRegistrar, srv RoleAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedRoleAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoleAdminService_ServiceDesc, srv)
}

func _RoleAdminService_AssignRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleAdminServiceServer).AssignRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleAdminService_AssignRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleAdminServiceServer).AssignRole(ctx, req.(*AssignRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoleAdminService_RevokeRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleAdminServiceServer).RevokeRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoleAdminService_RevokeRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleAdminServiceServer).RevokeRole(ctx, req.(*RevokeRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoleAdminService_ServiceDesc is the grpc.ServiceDesc for RoleAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoleAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idm.v1.RoleAdminService",
	HandlerType: (*RoleAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignRole",
			Handler:    _RoleAdminService_AssignRole_Handler,
		},
		{
			MethodName: "RevokeRole",
			Handler:    _RoleAdminService_RevokeRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idm/v1/idm.proto",
}

const (
	IamAdminService_ListRoles_FullMethodName             = "/idm.v1.IamAdminService/ListRoles"
	IamAdminService_ListPermissions_FullMethodName       = "/idm.v1.IamAdminService/ListPermissions"
	IamAdminService_GetRolePermissions_FullMethodName    = "/idm.v1.IamAdminService/GetRolePermissions"
	IamAdminService_ListSubjectsWithRoles_FullMethodName = "/idm.v1.IamAdminService/ListSubjectsWithRoles"
	IamAdminService_GetSubjectRoles_FullMethodName       = "/idm.v1.IamAdminService/GetSubjectRoles"
)

// IamAdminServiceClient is the client API for IamAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IamAdminService — читающий контракт IAM-админки (ADR-0014): просмотр каталога
// ролей/прав и привязок субъект↔роль. Только чтение (без побочных эффектов на
// кэш решений). Путь привилегированный: gateway проверяет право (read,
// iam:global) перед КАЖДОЙ ручкой (fail-closed). Расширение аддитивно
// (wire-совместимо): новый сервис и сообщения, существующие RPC не меняются.
// Мутации привязок выполняет RoleAdminService (переиспользуется, не дублируется).
type IamAdminServiceClient interface {
	// ListRoles возвращает все роли каталога (без пагинации — справочник мал).
	ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error)
	// ListPermissions возвращает все права каталога (без пагинации).
	ListPermissions(ctx context.Context, in *ListPermissionsRequest, opts ...grpc.CallOption) (*ListPermissionsResponse, error)
	// GetRolePermissions возвращает права конкретной роли. Несуществующая роль →
	// NotFound; пустое имя → InvalidArgument.
	GetRolePermissions(ctx context.Context, in *GetRolePermissionsRequest, opts ...grpc.CallOption) (*GetRolePermissionsResponse, error)
	// ListSubjectsWithRoles перечисляет субъектов (DISTINCT subject из
	// subject_roles) с их ролями; keyset-пагинация по subject (ASC). Субъекты без
	// ролей системе неизвестны и не возвращаются.
	ListSubjectsWithRoles(ctx context.Context, in *ListSubjectsWithRolesRequest, opts ...grpc.CallOption) (*ListSubjectsWithRolesResponse, error)
	// GetSubjectRoles возвращает роли субъекта (пустой набор, не NotFound, если
	// ролей нет); пустой subject → InvalidArgument.
	GetSubjectRoles(ctx context.Context, in *GetSubjectRolesRequest, opts ...grpc.CallOption) (*GetSubjectRolesResponse, error)
}

type iamAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIamAdminServiceClient(cc grpc.ClientConnInterface) IamAdminServiceClient {
	return &iamAdminServiceClient{cc}
}

func (c *iamAdminServiceClient) ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRolesResponse)
	err := c.cc.Invoke(ctx, IamAdminService_ListRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamAdminServiceClient) ListPermissions(ctx context.Context, in *ListPermissionsRequest, opts ...grpc.CallOption) (*ListPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPermissionsResponse)
	err := c.cc.Invoke(ctx, IamAdminService_ListPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamAdminServiceClient) GetRolePermissions(ctx context.Context, in *GetRolePermissionsRequest, opts ...grpc.CallOption) (*GetRolePermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRolePermissionsResponse)
	err := c.cc.Invoke(ctx, IamAdminService_GetRolePermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamAdminServiceClient) ListSubjectsWithRoles(ctx context.Context, in *ListSubjectsWithRolesRequest, opts ...grpc.CallOption) (*ListSubjectsWithRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSubjectsWithRolesResponse)
	err := c.cc.Invoke(ctx, IamAdminService_ListSubjectsWithRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iamAdminServiceClient) GetSubjectRoles(ctx context.Context, in *GetSubjectRolesRequest, opts ...grpc.CallOption) (*GetSubjectRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubjectRolesResponse)
	err := c.cc.Invoke(ctx, IamAdminService_GetSubjectRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IamAdminServiceServer is the server API for IamAdminService service.
// All implementations must embed UnimplementedIamAdminServiceServer
// for forward compatibility.
//
// IamAdminService — читающий контракт IAM-админки (ADR-0014): просмотр каталога
// ролей/прав и привязок субъект↔роль. Только чтение (без побочных эффектов на
// кэш решений). Путь привилегированный: gateway проверяет право (read,
// iam:global) перед КАЖДОЙ ручкой (fail-closed). Расширение аддитивно
// (wire-совместимо): новый сервис и сообщения, существующие RPC не меняются.
// Мутации привязок выполняет RoleAdminService (переиспользуется, не дублируется).
type IamAdminServiceServer interface {
	// ListRoles возвращает все роли каталога (без пагинации — справочник мал).
	ListRoles(context.Context, *ListRolesRequest) (*ListRolesResponse, error)
	// ListPermissions возвращает все права каталога (без пагинации).
	ListPermissions(context.Context, *ListPermissionsRequest) (*ListPermissionsResponse, error)
	// GetRolePermissions возвращает права конкретной роли. Несуществующая роль →
	// NotFound; пустое имя → InvalidArgument.
	GetRolePermissions(context.Context, *GetRolePermissionsRequest) (*GetRolePermissionsResponse, error)
	// ListSubjectsWithRoles перечисляет субъектов (DISTINCT subject из
	// subject_roles) с их ролями; keyset-пагинация по subject (ASC). Субъекты без
	// ролей системе неизвестны и не возвращаются.
	ListSubjectsWithRoles(context.Context, *ListSubjectsWithRolesRequest) (*ListSubjectsWithRolesResponse, error)
	// GetSubjectRoles возвращает роли субъекта (пустой набор, не NotFound, если
	// ролей нет); пустой subject → InvalidArgument.
	GetSubjectRoles(context.Context, *GetSubjectRolesRequest) (*GetSubjectRolesResponse, error)
	mustEmbedUnimplementedIamAdminServiceServer()
}

// UnimplementedIamAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIamAdminServiceServer struct{}

func (UnimplementedIamAdminServiceServer) ListRoles(context.Context, *ListRolesRequest) (*ListRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoles not implemented")
}
func (UnimplementedIamAdminServiceServer) ListPermissions(context.Context, *ListPermissionsRequest) (*ListPermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPermissions not implemented")
}
func (UnimplementedIamAdminServiceServer) GetRolePermissions(context.Context, *GetRolePermissionsRequest) (*GetRolePermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRolePermissions not implemented")
}
func (UnimplementedIamAdminServiceServer) ListSubjectsWithRoles(context.Context, *ListSubjectsWithRolesRequest) (*ListSubjectsWithRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSubjectsWithRoles not implemented")
}
func (UnimplementedIamAdminServiceServer) GetSubjectRoles(context.Context, *GetSubjectRolesRequest) (*GetSubjectRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubjectRoles not implemented")
}
func (UnimplementedIamAdminServiceServer) mustEmbedUnimplementedIamAdminServiceServer() {}
func (UnimplementedIamAdminServiceServer) testEmbeddedByValue()                         {}

// UnsafeIamAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IamAdminServiceServer will
// result in compilation errors.
type UnsafeIamAdminServiceServer interface {
	mustEmbedUnimplementedIamAdminServiceServer()
}

func RegisterIamAdminServiceServer(s grpc.ServiceRegistrar, srv IamAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedIamAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IamAdminService_ServiceDesc, srv)
}

func _IamAdminService_ListRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamAdminServiceServer).ListRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamAdminService_ListRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamAdminServiceServer).ListRoles(ctx, req.(*ListRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamAdminService_ListPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamAdminServiceServer).ListPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamAdminService_ListPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamAdminServiceServer).ListPermissions(ctx, req.(*ListPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamAdminService_GetRolePermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolePermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamAdminServiceServer).GetRolePermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamAdminService_GetRolePermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamAdminServiceServer).GetRolePermissions(ctx, req.(*GetRolePermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamAdminService_ListSubjectsWithRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubjectsWithRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamAdminServiceServer).ListSubjectsWithRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamAdminService_ListSubjectsWithRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamAdminServiceServer).ListSubjectsWithRoles(ctx, req.(*ListSubjectsWithRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IamAdminService_GetSubjectRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubjectRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IamAdminServiceServer).GetSubjectRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IamAdminService_GetSubjectRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IamAdminServiceServer).GetSubjectRoles(ctx, req.(*GetSubjectRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IamAdminService_ServiceDesc is the grpc.ServiceDesc for IamAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IamAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "idm.v1.IamAdminService",
	HandlerType: (*IamAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRoles",
			Handler:    _IamAdminService_ListRoles_Handler,
		},
		{
			MethodName: "ListPermissions",
			Handler:    _IamAdminService_ListPermissions_Handler,
		},
		{
			MethodName: "GetRolePermissions",
			Handler:    _IamAdminService_GetRolePermissions_Handler,
		},
		{
			MethodName: "ListSubjectsWithRoles",
			Handler:    _IamAdminService_ListSubjectsWithRoles_Handler,
		},
		{
			MethodName: "GetSubjectRoles",
			Handler:    _IamAdminService_GetSubjectRoles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idm/v1/idm.proto",
}
