// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: projects/v1/projects.proto

// Пакет projects.v1 — контракт сервиса управления проектами для внутренних
// вызовов gateway↔projects (ADR-0002). В этом изменении — КАРКАС: типы и
// сигнатуры без доменной реализации (создание/перенос/удаление — отдельные
// changes). Статусы сервиса перечислены здесь как контракт (ADR-0004).

package projectsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServiceStatus — статус создаваемой единицы (сервиса) в каталоге.
// Zero-value намеренно UNSPECIFIED (не маппить незнакомое в дефолт молча).
type ServiceStatus int32

const (
	ServiceStatus_SERVICE_STATUS_UNSPECIFIED    ServiceStatus = 0
	ServiceStatus_SERVICE_STATUS_CREATING       ServiceStatus = 1
	ServiceStatus_SERVICE_STATUS_ACTIVE         ServiceStatus = 2
	ServiceStatus_SERVICE_STATUS_DECOMMISSIONED ServiceStatus = 3
	ServiceStatus_SERVICE_STATUS_FAILED         ServiceStatus = 4
	// SERVICE_STATUS_TRANSFERRING — транзитный статус на время переноса сервиса в
	// другой проект (ADR-0013). Защищает от конкурентных операций (guarded-CAS
	// active→transferring) и даёт наблюдаемость незавершённого переноса.
	// Аддитивное значение (новый номер 5; существующие значения не меняются).
	ServiceStatus_SERVICE_STATUS_TRANSFERRING ServiceStatus = 5
)

// Enum value maps for ServiceStatus.
var (
	ServiceStatus_name = map[int32]string{
		0: "SERVICE_STATUS_UNSPECIFIED",
		1: "SERVICE_STATUS_CREATING",
		2: "SERVICE_STATUS_ACTIVE",
		3: "SERVICE_STATUS_DECOMMISSIONED",
		4: "SERVICE_STATUS_FAILED",
		5: "SERVICE_STATUS_TRANSFERRING",
	}
	ServiceStatus_value = map[string]int32{
		"SERVICE_STATUS_UNSPECIFIED":    0,
		"SERVICE_STATUS_CREATING":       1,
		"SERVICE_STATUS_ACTIVE":         2,
		"SERVICE_STATUS_DECOMMISSIONED": 3,
		"SERVICE_STATUS_FAILED":         4,
		"SERVICE_STATUS_TRANSFERRING":   5,
	}
)

func (x ServiceStatus) Enum() *ServiceStatus {
	p := new(ServiceStatus)
	*p = x
	return p
}

func (x ServiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_projects_v1_projects_proto_enumTypes[0].Descriptor()
}

func (ServiceStatus) Type() protoreflect.EnumType {
	return &file_projects_v1_projects_proto_enumTypes[0]
}

func (x ServiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceStatus.Descriptor instead.
func (ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_projects_v1_projects_proto_rawDescGZIP(), []int{0}
}

// Service — запись каталога (единица-сервис).
type Service struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// project — идентификатор проекта-владельца.
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// name — имя сервиса внутри проекта.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// status — текущий статус записи.
	Status ServiceStatus `protobuf:"varint,3,opt,name=status,proto3,enum=projects.v1.ServiceStatus" json:"status,omitempty"`
	// owners — текущий набор владельцев сервиса (детерминированный порядок).
	Owners []string `protobuf:"bytes,4,rep,name=owners,proto3" json:"owners,omitempty"`
	// owners_version — версия набора владельцев для optimistic-concurrency.
	OwnersVersion int64 `protobuf:"varint,5,opt,name=owners_version,json=ownersVersion,proto3" json:"owners_version,omitempty"`
	// decommissioned_at — момент вывода сервиса из эксплуатации (RFC3339); пусто,
	// если сервис не выведен. Аддитивное поле (ADR-0012).
	DecommissionedAt string `protobuf:"bytes,6,opt,name=decommissioned_at,json=decommissionedAt,proto3" json:"decommissioned_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_projects_v1_projects_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_projects_v1_projects_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_projects_v1_projects_proto_rawDescGZIP(), []int{0}
}

func (x *Service) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetStatus() ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ServiceStatus_SERVICE_STATUS_UNSPECIFIED
}

func (x *Service) GetOwners() []string {
	if x != nil {
		return x.Owners
	}
	return nil
}

func (x *Service) GetOwnersVersion() int64 {
	if x != nil {
		return x.OwnersVersion
	}
	return 0
}

func (x *Service) GetDecommissionedAt() string {
	if x != nil {
		return x.DecommissionedAt
	}
	return ""
}

type GetServiceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// project — идентификатор проекта.
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// name — имя сервиса внутри проекта.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceRequest) Reset() {
	*x = GetServiceRequest{}
	mi := &file_projects_v1_projects_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceRequest) ProtoMessage() {}

func (x *GetServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projects_v1_projects_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceRequest.ProtoReflect.Descriptor instead.
func (*GetServiceRequest) Descriptor() ([]byte, []int) {
	return file_projects_v1_projects_proto_rawDescGZIP(), []int{1}
}

func (x *GetServiceRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *GetServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetServiceResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Project string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Name    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status  ServiceStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=projects.v1.ServiceStatus" json:"status,omitempty"`
	// owners — текущий набор владельцев (детерминированный порядок).
	Owners []string `protobuf:"bytes,4,rep,name=owners,proto3" json:"owners,omitempty"`
	// owners_version — версия набора владельцев для optimistic-concurrency.
	OwnersVersion int64 `protobuf:"varint,5,opt,name=owners_version,json=ownersVersion,proto3" json:"owners_version,omitempty"`
	// decommissioned_at — момент вывода сервиса из эксплуатации (RFC3339); пусто,
	// если сервис не выведен. Аддитивное поле (ADR-0012).
	DecommissionedAt string `protobuf:"bytes,6,opt,name=decommissioned_at,json=decommissionedAt,proto3" json:"decommissioned_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetServiceResponse) Reset() {
	*x = GetServiceResponse{}
	mi := &file_projects_v1_projects_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceResponse) ProtoMessage() {}

func (x *GetServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projects_v1_projects_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceResponse.ProtoReflect.Descriptor instead.
func (*GetServiceResponse) Descriptor() ([]byte, []int) {
	return file_projects_v1_projects_proto_rawDescGZIP(), []int{2}
}

func (x *GetServiceResponse) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *GetServiceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetServiceResponse) GetStatus() ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ServiceStatus_SERVICE_STATUS_UNSPECIFIED
}

func (x *GetServiceResponse) GetOwners() []string {
	if x != nil {
		return x.Owners
	}
	return nil
}

func (x *GetServiceResponse) GetOwnersVersion() int64 {
	if x != nil {
		return x.OwnersVersion
	}
	return 0
}

func (x *GetServiceResponse) GetDecommissionedAt() string {
	if x != nil {
		return x.DecommissionedAt
	}
	return ""
}

type ListServicesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// project — идентификатор проекта, чьи сервисы перечисляются.
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// page_size — желаемый размер страницы; сервер клампит к допустимому пределу.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// page_token — непрозрачный курсор продолжения из предыдущего ответа;
	// пустой — с начала.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_projects_v1_projects_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projects_v1_projects_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_projects_v1_projects_proto_rawDescGZIP(), []int{3}
}

func (x *ListServicesRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ListServicesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListServicesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListServicesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// services — страница записей в порядке (created_at, id).
	Services []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	// next_page_token — курсор следующей страницы; пустой — конец выборки.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_projects_v1_projects_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projects_v1_projects_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_projects_v1_projects_proto_rawDescGZIP(), []int{4}
}

func (x *ListServicesResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ListServicesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateServiceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// project — идентификатор проекта-владельца.
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// name — имя создаваемого сервиса внутри проекта.
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceRequest) Reset() {
	*x = CreateServiceRequest{}
	mi := &file_projects_v1_projects_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceRequest) ProtoMessage() {}

func (x *CreateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projects_v1_projects_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return file_projects_v1_projects_proto_rawDescGZIP(), []int{5}
}

func (x *CreateServiceRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *CreateServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateServiceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id — идентификатор созданной записи каталога (UUID в строковом виде).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// status — стартовый статус записи; сразу после запуска — CREATING.
	Status        ServiceStatus `protobuf:"varint,2,opt,name=status,proto3,enum=projects.v1.ServiceStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceResponse) Reset() {
	*x = CreateServiceResponse{}
	mi := &file_projects_v1_projects_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceResponse) ProtoMessage() {}

func (x *CreateServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projects_v1_projects_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceResponse.ProtoReflect.Descriptor instead.
func (*CreateServiceResponse) Descriptor() ([]byte, []int) {
	return file_projects_v1_projects_proto_rawDescGZIP(), []int{6}
}

func (x *CreateServiceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateServiceResponse) GetStatus() ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ServiceStatus_SERVICE_STATUS_UNSPECIFIED
}

type SetServiceOwnersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// project — идентификатор проекта-владельца.
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// name — имя сервиса внутри проекта.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// owners — полный желаемый набор владельцев (декларативно). Сервер нормализует
	// (без пустых строк и дублей) и вычисляет diff против текущего состояния.
	Owners []string `protobuf:"bytes,3,rep,name=owners,proto3" json:"owners,omitempty"`
	// expected_version — ожидаемая версия набора владельцев (optimistic-concurrency).
	// Несовпадение с актуальной версией → FailedPrecondition.
	ExpectedVersion int64 `protobuf:"varint,4,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetServiceOwnersRequest) Reset() {
	*x = SetServiceOwnersRequest{}
	mi := &file_projects_v1_projects_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetServiceOwnersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetServiceOwnersRequest) ProtoMessage() {}

func (x *SetServiceOwnersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projects_v1_projects_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetServiceOwnersRequest.ProtoReflect.Descriptor instead.
func (*SetServiceOwnersRequest) Descriptor() ([]byte, []int) {
	return file_projects_v1_projects_proto_rawDescGZIP(), []int{7}
}

func (x *SetServiceOwnersRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *SetServiceOwnersRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetServiceOwnersRequest) GetOwners() []string {
	if x != nil {
		return x.Owners
	}
	return nil
}

func (x *SetServiceOwnersRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type SetServiceOwnersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// owners — итоговый набор владельцев после применения (детерминированный порядок).
	Owners []string `protobuf:"bytes,1,rep,name=owners,proto3" json:"owners,omitempty"`
	// owners_version — новая версия набора владельцев.
	OwnersVersion int64 `protobuf:"varint,2,opt,name=owners_version,json=ownersVersion,proto3" json:"owners_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetServiceOwnersResponse) Reset() {
	*x = SetServiceOwnersResponse{}
	mi := &file_projects_v1_projects_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetServiceOwnersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetServiceOwnersResponse) ProtoMessage() {}

func (x *SetServiceOwnersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projects_v1_projects_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetServiceOwnersResponse.ProtoReflect.Descriptor instead.
func (*SetServiceOwnersResponse) Descriptor() ([]byte, []int) {
	return file_projects_v1_projects_proto_rawDescGZIP(), []int{8}
}

func (x *SetServiceOwnersResponse) GetOwners() []string {
	if x != nil {
		return x.Owners
	}
	return nil
}

func (x *SetServiceOwnersResponse) GetOwnersVersion() int64 {
	if x != nil {
		return x.OwnersVersion
	}
	return 0
}

type DecommissionServiceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// project — идентификатор проекта-владельца.
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// name — имя выводимого из эксплуатации сервиса.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// load_drained — явное предусловие: нагрузка сервиса снята из K8s. В MVP
	// K8s-worker отсутствует, поэтому снятие нагрузки подтверждается вызывающей
	// стороной (ADR-0012). false → FailedPrecondition до любых побочных эффектов.
	LoadDrained   bool `protobuf:"varint,3,opt,name=load_drained,json=loadDrained,proto3" json:"load_drained,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecommissionServiceRequest) Reset() {
	*x = DecommissionServiceRequest{}
	mi := &file_projects_v1_projects_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecommissionServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecommissionServiceRequest) ProtoMessage() {}

func (x *DecommissionServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projects_v1_projects_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecommissionServiceRequest.ProtoReflect.Descriptor instead.
func (*DecommissionServiceRequest) Descriptor() ([]byte, []int) {
	return file_projects_v1_projects_proto_rawDescGZIP(), []int{9}
}

func (x *DecommissionServiceRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *DecommissionServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DecommissionServiceRequest) GetLoadDrained() bool {
	if x != nil {
		return x.LoadDrained
	}
	return false
}

type DecommissionServiceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// service — итоговое состояние записи (status=DECOMMISSIONED, decommissioned_at).
	Service       *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecommissionServiceResponse) Reset() {
	*x = DecommissionServiceResponse{}
	mi := &file_projects_v1_projects_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecommissionServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecommissionServiceResponse) ProtoMessage() {}

func (x *DecommissionServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projects_v1_projects_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecommissionServiceResponse.ProtoReflect.Descriptor instead.
func (*DecommissionServiceResponse) Descriptor() ([]byte, []int) {
	return file_projects_v1_projects_proto_rawDescGZIP(), []int{10}
}

func (x *DecommissionServiceResponse) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

type TransferServiceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// project — исходный проект-владелец (source), из которого переносится сервис.
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// name — имя переносимого сервиса (сохраняется при переносе).
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// target_project — целевой проект-владелец (target), в который переносится
	// сервис. Должен отличаться от project; пара (target_project, name) должна быть
	// свободна, иначе конфликт.
	TargetProject string `protobuf:"bytes,3,opt,name=target_project,json=targetProject,proto3" json:"target_project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferServiceRequest) Reset() {
	*x = TransferServiceRequest{}
	mi := &file_projects_v1_projects_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferServiceRequest) ProtoMessage() {}

func (x *TransferServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projects_v1_projects_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferServiceRequest.ProtoReflect.Descriptor instead.
func (*TransferServiceRequest) Descriptor() ([]byte, []int) {
	return file_projects_v1_projects_proto_rawDescGZIP(), []int{11}
}

func (x *TransferServiceRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *TransferServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TransferServiceRequest) GetTargetProject() string {
	if x != nil {
		return x.TargetProject
	}
	return ""
}

type TransferServiceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// service — итоговое состояние записи (project=target_project, status=ACTIVE).
	Service       *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferServiceResponse) Reset() {
	*x = TransferServiceResponse{}
	mi := &file_projects_v1_projects_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferServiceResponse) ProtoMessage() {}

func (x *TransferServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projects_v1_projects_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferServiceResponse.ProtoReflect.Descriptor instead.
func (*TransferServiceResponse) Descriptor() ([]byte, []int) {
	return file_projects_v1_projects_proto_rawDescGZIP(), []int{12}
}

func (x *TransferServiceResponse) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

var File_projects_v1_projects_proto protoreflect.FileDescriptor

const file_projects_v1_projects_proto_rawDesc = "" +
	"\n" +
	"\x1aprojects/v1/projects.proto\x12\vprojects.v1\"\xd7\x01\n" +
	"\aService\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x122\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1a.projects.v1.ServiceStatusR\x06status\x12\x16\n" +
	"\x06owners\x18\x04 \x03(\tR\x06owners\x12%\n" +
	"\x0eowners_version\x18\x05 \x01(\x03R\rownersVersion\x12+\n" +
	"\x11decommissioned_at\x18\x06 \x01(\tR\x10decommissionedAt\"A\n" +
	"\x11GetServiceRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xe2\x01\n" +
	"\x12GetServiceResponse\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x122\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1a.projects.v1.ServiceStatusR\x06status\x12\x16\n" +
	"\x06owners\x18\x04 \x03(\tR\x06owners\x12%\n" +
	"\x0eowners_version\x18\x05 \x01(\x03R\rownersVersion\x12+\n" +
	"\x11decommissioned_at\x18\x06 \x01(\tR\x10decommissionedAt\"k\n" +
	"\x13ListServicesRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"p\n" +
	"\x14ListServicesResponse\x120\n" +
	"\bservices\x18\x01 \x03(\v2\x14.projects.v1.ServiceR\bservices\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"D\n" +
	"\x14CreateServiceRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"[\n" +
	"\x15CreateServiceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.projects.v1.ServiceStatusR\x06status\"\x8a\x01\n" +
	"\x17SetServiceOwnersRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06owners\x18\x03 \x03(\tR\x06owners\x12)\n" +
	"\x10expected_version\x18\x04 \x01(\x03R\x0fexpectedVersion\"Y\n" +
	"\x18SetServiceOwnersResponse\x12\x16\n" +
	"\x06owners\x18\x01 \x03(\tR\x06owners\x12%\n" +
	"\x0eowners_version\x18\x02 \x01(\x03R\rownersVersion\"m\n" +
	"\x1aDecommissionServiceRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fload_drained\x18\x03 \x01(\bR\vloadDrained\"M\n" +
	"\x1bDecommissionServiceResponse\x12.\n" +
	"\aservice\x18\x01 \x01(\v2\x14.projects.v1.ServiceR\aservice\"m\n" +
	"\x16TransferServiceRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0etarget_project\x18\x03 \x01(\tR\rtargetProject\"I\n" +
	"\x17TransferServiceResponse\x12.\n" +
	"\aservice\x18\x01 \x01(\v2\x14.projects.v1.ServiceR\aservice*\xc6\x01\n" +
	"\rServiceStatus\x12\x1e\n" +
	"\x1aSERVICE_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SERVICE_STATUS_CREATING\x10\x01\x12\x19\n" +
	"\x15SERVICE_STATUS_ACTIVE\x10\x02\x12!\n" +
	"\x1dSERVICE_STATUS_DECOMMISSIONED\x10\x03\x12\x19\n" +
	"\x15SERVICE_STATUS_FAILED\x10\x04\x12\x1f\n" +
	"\x1bSERVICE_STATUS_TRANSFERRING\x10\x052\xb6\x04\n" +
	"\x0fProjectsService\x12M\n" +
	"\n" +
	"GetService\x12\x1e.projects.v1.GetServiceRequest\x1a\x1f.projects.v1.GetServiceResponse\x12S\n" +
	"\fListServices\x12 .projects.v1.ListServicesRequest\x1a!.projects.v1.ListServicesResponse\x12V\n" +
	"\rCreateService\x12!.projects.v1.CreateServiceRequest\x1a\".projects.v1.CreateServiceResponse\x12_\n" +
	"\x10SetServiceOwners\x12$.projects.v1.SetServiceOwnersRequest\x1a%.projects.v1.SetServiceOwnersResponse\x12h\n" +
	"\x13DecommissionService\x12'.projects.v1.DecommissionServiceRequest\x1a(.projects.v1.DecommissionServiceResponse\x12\\\n" +
	"\x0fTransferService\x12#.projects.v1.TransferServiceRequest\x1a$.projects.v1.TransferServiceResponseB6Z4github.com/YuriB9/idp/pkg/api/projects/v1;projectsv1b\x06proto3"

var (
	file_projects_v1_projects_proto_rawDescOnce sync.Once
	file_projects_v1_projects_proto_rawDescData []byte
)

func file_projects_v1_projects_proto_rawDescGZIP() []byte {
	file_projects_v1_projects_proto_rawDescOnce.Do(func() {
		file_projects_v1_projects_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_projects_v1_projects_proto_rawDesc), len(file_projects_v1_projects_proto_rawDesc)))
	})
	return file_projects_v1_projects_proto_rawDescData
}

var file_projects_v1_projects_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_projects_v1_projects_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_projects_v1_projects_proto_goTypes = []any{
	(ServiceStatus)(0),                  // 0: projects.v1.ServiceStatus
	(*Service)(nil),                     // 1: projects.v1.Service
	(*GetServiceRequest)(nil),           // 2: projects.v1.GetServiceRequest
	(*GetServiceResponse)(nil),          // 3: projects.v1.GetServiceResponse
	(*ListServicesRequest)(nil),         // 4: projects.v1.ListServicesRequest
	(*ListServicesResponse)(nil),        // 5: projects.v1.ListServicesResponse
	(*CreateServiceRequest)(nil),        // 6: projects.v1.CreateServiceRequest
	(*CreateServiceResponse)(nil),       // 7: projects.v1.CreateServiceResponse
	(*SetServiceOwnersRequest)(nil),     // 8: projects.v1.SetServiceOwnersRequest
	(*SetServiceOwnersResponse)(nil),    // 9: projects.v1.SetServiceOwnersResponse
	(*DecommissionServiceRequest)(nil),  // 10: projects.v1.DecommissionServiceRequest
	(*DecommissionServiceResponse)(nil), // 11: projects.v1.DecommissionServiceResponse
	(*TransferServiceRequest)(nil),      // 12: projects.v1.TransferServiceRequest
	(*TransferServiceResponse)(nil),     // 13: projects.v1.TransferServiceResponse
}
var file_projects_v1_projects_proto_depIdxs = []int32{
	0,  // 0: projects.v1.Service.status:type_name -> projects.v1.ServiceStatus
	0,  // 1: projects.v1.GetServiceResponse.status:type_name -> projects.v1.ServiceStatus
	1,  // 2: projects.v1.ListServicesResponse.services:type_name -> projects.v1.Service
	0,  // 3: projects.v1.CreateServiceResponse.status:type_name -> projects.v1.ServiceStatus
	1,  // 4: projects.v1.DecommissionServiceResponse.service:type_name -> projects.v1.Service
	1,  // 5: projects.v1.TransferServiceResponse.service:type_name -> projects.v1.Service
	2,  // 6: projects.v1.ProjectsService.GetService:input_type -> projects.v1.GetServiceRequest
	4,  // 7: projects.v1.ProjectsService.ListServices:input_type -> projects.v1.ListServicesRequest
	6,  // 8: projects.v1.ProjectsService.CreateService:input_type -> projects.v1.CreateServiceRequest
	8,  // 9: projects.v1.ProjectsService.SetServiceOwners:input_type -> projects.v1.SetServiceOwnersRequest
	10, // 10: projects.v1.ProjectsService.DecommissionService:input_type -> projects.v1.DecommissionServiceRequest
	12, // 11: projects.v1.ProjectsService.TransferService:input_type -> projects.v1.TransferServiceRequest
	3,  // 12: projects.v1.ProjectsService.GetService:output_type -> projects.v1.GetServiceResponse
	5,  // 13: projects.v1.ProjectsService.ListServices:output_type -> projects.v1.ListServicesResponse
	7,  // 14: projects.v1.ProjectsService.CreateService:output_type -> projects.v1.CreateServiceResponse
	9,  // 15: projects.v1.ProjectsService.SetServiceOwners:output_type -> projects.v1.SetServiceOwnersResponse
	11, // 16: projects.v1.ProjectsService.DecommissionService:output_type -> projects.v1.DecommissionServiceResponse
	13, // 17: projects.v1.ProjectsService.TransferService:output_type -> projects.v1.TransferServiceResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_projects_v1_projects_proto_init() }
func file_projects_v1_projects_proto_init() {
	if File_projects_v1_projects_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_projects_v1_projects_proto_rawDesc), len(file_projects_v1_projects_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_projects_v1_projects_proto_goTypes,
		DependencyIndexes: file_projects_v1_projects_proto_depIdxs,
		EnumInfos:         file_projects_v1_projects_proto_enumTypes,
		MessageInfos:      file_projects_v1_projects_proto_msgTypes,
	}.Build()
	File_projects_v1_projects_proto = out.File
	file_projects_v1_projects_proto_goTypes = nil
	file_projects_v1_projects_proto_depIdxs = nil
}
