// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: projects/v1/projects.proto

// Пакет projects.v1 — контракт сервиса управления проектами для внутренних
// вызовов gateway↔projects (ADR-0002). В этом изменении — КАРКАС: типы и
// сигнатуры без доменной реализации (создание/перенос/удаление — отдельные
// changes). Статусы сервиса перечислены здесь как контракт (ADR-0004).

package projectsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProjectsService_GetService_FullMethodName          = "/projects.v1.ProjectsService/GetService"
	ProjectsService_ListServices_FullMethodName        = "/projects.v1.ProjectsService/ListServices"
	ProjectsService_CreateService_FullMethodName       = "/projects.v1.ProjectsService/CreateService"
	ProjectsService_SetServiceOwners_FullMethodName    = "/projects.v1.ProjectsService/SetServiceOwners"
	ProjectsService_DecommissionService_FullMethodName = "/projects.v1.ProjectsService/DecommissionService"
	ProjectsService_TransferService_FullMethodName     = "/projects.v1.ProjectsService/TransferService"
)

// ProjectsServiceClient is the client API for ProjectsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProjectsService — интерфейс каталога. Чтение (GetService/ListServices) и
// запуск создания сервиса (CreateService → стартует Temporal-workflow провизии,
// исполняемый DevInfra worker'ом, ADR-0001). Доменные user stories переноса и
// удаления добавляются последующими changes.
type ProjectsServiceClient interface {
	// GetService возвращает текущее состояние сервиса из каталога.
	// Отсутствие записи отображается в gRPC-статус NotFound.
	GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*GetServiceResponse, error)
	// ListServices возвращает страницу сервисов проекта с keyset-пагинацией
	// по непрозрачному курсору (сортировка по (created_at, id)).
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	// CreateService фиксирует запись каталога со статусом CREATING и запускает
	// Temporal-workflow «Создание сервиса» (детерминированный WorkflowID для
	// идемпотентности повторного запуска). Возвращает идентификатор записи и
	// стартовый статус CREATING. Сама провизия (GitLab/Vault/Harbor) выполняется
	// асинхронно worker'ом; финальный статус (ACTIVE/FAILED) — по завершении
	// workflow. BREAKING: добавление метода в существующий сервис-контракт.
	CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*CreateServiceResponse, error)
	// SetServiceOwners декларативно заменяет набор владельцев сервиса: клиент шлёт
	// полный желаемый набор owners и ожидаемую версию owners_version
	// (optimistic-concurrency). Сервер вычисляет diff и запускает Temporal-workflow
	// «Изменение владельцев» с детерминированным WorkflowID (идемпотентность
	// повторного запуска). Синхронизация GitLab/Vault/IDM выполняется асинхронно
	// worker'ом. Конфликт версии → FailedPrecondition; отсутствие записи →
	// NotFound. BREAKING: добавление метода в существующий сервис-контракт.
	SetServiceOwners(ctx context.Context, in *SetServiceOwnersRequest, opts ...grpc.CallOption) (*SetServiceOwnersResponse, error)
	// DecommissionService выводит активный сервис из эксплуатации (soft delete):
	// данные каталога СОХРАНЯЮТСЯ, статус переводится guarded-CAS ACTIVE→DECOMMISSIONED,
	// во внешних системах отзывается доступ (GitLab archive, Harbor read-only, Vault
	// revoke SecretID) — асинхронно Temporal-workflow «Вывод из эксплуатации» с
	// детерминированным WorkflowID. Поле load_drained — явное предусловие снятой
	// нагрузки из K8s (в MVP K8s-worker нет, см. ADR-0012). Семантика идемпотентна:
	// повторный вызов на уже выведенном сервисе → успех (no-op). Допустимый исходный
	// статус — только ACTIVE; creating/failed или неснятая нагрузка →
	// FailedPrecondition; конкурентная смена статуса → Aborted; отсутствие записи →
	// NotFound. BREAKING: добавление метода в существующий сервис-контракт.
	DecommissionService(ctx context.Context, in *DecommissionServiceRequest, opts ...grpc.CallOption) (*DecommissionServiceResponse, error)
	// TransferService переносит сервис в другой проект (смена project-владельца):
	// id записи каталога СОХРАНЯЕТСЯ, меняется колонка project (source→target),
	// владельцы переезжают вместе с записью. Перенос выполняется асинхронно
	// Temporal-workflow «Перенос» (Saga) с детерминированным WorkflowID: каталог
	// active→transferring → перенос репозитория GitLab в новую группу (ТОЧКА
	// НЕВОЗВРАТА) → миграция путей/политик Vault → обновление метаданных Harbor →
	// каталог transferring→active (project=target) → перенос ролей владельцев в IDM.
	// Требует ДВУХ прав: transfer на исходном проекте И transfer_in на целевом
	// (ADR-0013). Семантика идемпотентна: повторный вызов на уже перенесённом
	// сервисе (project уже равен target) → успех (no-op). Допустимый исходный
	// статус — только ACTIVE; creating/failed/decommissioned/transferring →
	// FailedPrecondition; занятое имя в target или конкурентная смена статуса →
	// Aborted; отсутствие записи → NotFound. BREAKING: добавление метода в
	// существующий сервис-контракт.
	TransferService(ctx context.Context, in *TransferServiceRequest, opts ...grpc.CallOption) (*TransferServiceResponse, error)
}

type projectsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectsServiceClient(cc grpc.ClientConnInterface) ProjectsServiceClient {
	return &projectsServiceClient{cc}
}

func (c *projectsServiceClient) GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*GetServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceResponse)
	err := c.cc.Invoke(ctx, ProjectsService_GetService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsServiceClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, ProjectsService_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsServiceClient) CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*CreateServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateServiceResponse)
	err := c.cc.Invoke(ctx, ProjectsService_CreateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsServiceClient) SetServiceOwners(ctx context.Context, in *SetServiceOwnersRequest, opts ...grpc.CallOption) (*SetServiceOwnersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetServiceOwnersResponse)
	err := c.cc.Invoke(ctx, ProjectsService_SetServiceOwners_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsServiceClient) DecommissionService(ctx context.Context, in *DecommissionServiceRequest, opts ...grpc.CallOption) (*DecommissionServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecommissionServiceResponse)
	err := c.cc.Invoke(ctx, ProjectsService_DecommissionService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectsServiceClient) TransferService(ctx context.Context, in *TransferServiceRequest, opts ...grpc.CallOption) (*TransferServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferServiceResponse)
	err := c.cc.Invoke(ctx, ProjectsService_TransferService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectsServiceServer is the server API for ProjectsService service.
// All implementations must embed UnimplementedProjectsServiceServer
// for forward compatibility.
//
// ProjectsService — интерфейс каталога. Чтение (GetService/ListServices) и
// запуск создания сервиса (CreateService → стартует Temporal-workflow провизии,
// исполняемый DevInfra worker'ом, ADR-0001). Доменные user stories переноса и
// удаления добавляются последующими changes.
type ProjectsServiceServer interface {
	// GetService возвращает текущее состояние сервиса из каталога.
	// Отсутствие записи отображается в gRPC-статус NotFound.
	GetService(context.Context, *GetServiceRequest) (*GetServiceResponse, error)
	// ListServices возвращает страницу сервисов проекта с keyset-пагинацией
	// по непрозрачному курсору (сортировка по (created_at, id)).
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	// CreateService фиксирует запись каталога со статусом CREATING и запускает
	// Temporal-workflow «Создание сервиса» (детерминированный WorkflowID для
	// идемпотентности повторного запуска). Возвращает идентификатор записи и
	// стартовый статус CREATING. Сама провизия (GitLab/Vault/Harbor) выполняется
	// асинхронно worker'ом; финальный статус (ACTIVE/FAILED) — по завершении
	// workflow. BREAKING: добавление метода в существующий сервис-контракт.
	CreateService(context.Context, *CreateServiceRequest) (*CreateServiceResponse, error)
	// SetServiceOwners декларативно заменяет набор владельцев сервиса: клиент шлёт
	// полный желаемый набор owners и ожидаемую версию owners_version
	// (optimistic-concurrency). Сервер вычисляет diff и запускает Temporal-workflow
	// «Изменение владельцев» с детерминированным WorkflowID (идемпотентность
	// повторного запуска). Синхронизация GitLab/Vault/IDM выполняется асинхронно
	// worker'ом. Конфликт версии → FailedPrecondition; отсутствие записи →
	// NotFound. BREAKING: добавление метода в существующий сервис-контракт.
	SetServiceOwners(context.Context, *SetServiceOwnersRequest) (*SetServiceOwnersResponse, error)
	// DecommissionService выводит активный сервис из эксплуатации (soft delete):
	// данные каталога СОХРАНЯЮТСЯ, статус переводится guarded-CAS ACTIVE→DECOMMISSIONED,
	// во внешних системах отзывается доступ (GitLab archive, Harbor read-only, Vault
	// revoke SecretID) — асинхронно Temporal-workflow «Вывод из эксплуатации» с
	// детерминированным WorkflowID. Поле load_drained — явное предусловие снятой
	// нагрузки из K8s (в MVP K8s-worker нет, см. ADR-0012). Семантика идемпотентна:
	// повторный вызов на уже выведенном сервисе → успех (no-op). Допустимый исходный
	// статус — только ACTIVE; creating/failed или неснятая нагрузка →
	// FailedPrecondition; конкурентная смена статуса → Aborted; отсутствие записи →
	// NotFound. BREAKING: добавление метода в существующий сервис-контракт.
	DecommissionService(context.Context, *DecommissionServiceRequest) (*DecommissionServiceResponse, error)
	// TransferService переносит сервис в другой проект (смена project-владельца):
	// id записи каталога СОХРАНЯЕТСЯ, меняется колонка project (source→target),
	// владельцы переезжают вместе с записью. Перенос выполняется асинхронно
	// Temporal-workflow «Перенос» (Saga) с детерминированным WorkflowID: каталог
	// active→transferring → перенос репозитория GitLab в новую группу (ТОЧКА
	// НЕВОЗВРАТА) → миграция путей/политик Vault → обновление метаданных Harbor →
	// каталог transferring→active (project=target) → перенос ролей владельцев в IDM.
	// Требует ДВУХ прав: transfer на исходном проекте И transfer_in на целевом
	// (ADR-0013). Семантика идемпотентна: повторный вызов на уже перенесённом
	// сервисе (project уже равен target) → успех (no-op). Допустимый исходный
	// статус — только ACTIVE; creating/failed/decommissioned/transferring →
	// FailedPrecondition; занятое имя в target или конкурентная смена статуса →
	// Aborted; отсутствие записи → NotFound. BREAKING: добавление метода в
	// существующий сервис-контракт.
	TransferService(context.Context, *TransferServiceRequest) (*TransferServiceResponse, error)
	mustEmbedUnimplementedProjectsServiceServer()
}

// UnimplementedProjectsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProjectsServiceServer struct{}

func (UnimplementedProjectsServiceServer) GetService(context.Context, *GetServiceRequest) (*GetServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetService not implemented")
}
func (UnimplementedProjectsServiceServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedProjectsServiceServer) CreateService(context.Context, *CreateServiceRequest) (*CreateServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateService not implemented")
}
func (UnimplementedProjectsServiceServer) SetServiceOwners(context.Context, *SetServiceOwnersRequest) (*SetServiceOwnersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetServiceOwners not implemented")
}
func (UnimplementedProjectsServiceServer) DecommissionService(context.Context, *DecommissionServiceRequest) (*DecommissionServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecommissionService not implemented")
}
func (UnimplementedProjectsServiceServer) TransferService(context.Context, *TransferServiceRequest) (*TransferServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferService not implemented")
}
func (UnimplementedProjectsServiceServer) mustEmbedUnimplementedProjectsServiceServer() {}
func (UnimplementedProjectsServiceServer) testEmbeddedByValue()                         {}

// UnsafeProjectsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectsServiceServer will
// result in compilation errors.
type UnsafeProjectsServiceServer interface {
	mustEmbedUnimplementedProjectsServiceServer()
}

func RegisterProjectsServiceServer(s grpc.ServiceRegistrar, srv ProjectsServiceServer) {
	// If the following call panics, it indicates UnimplementedProjectsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProjectsService_ServiceDesc, srv)
}

func _ProjectsService_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServiceServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectsService_GetService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServiceServer).GetService(ctx, req.(*GetServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectsService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectsService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServiceServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectsService_CreateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServiceServer).CreateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectsService_CreateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServiceServer).CreateService(ctx, req.(*CreateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectsService_SetServiceOwners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetServiceOwnersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServiceServer).SetServiceOwners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectsService_SetServiceOwners_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServiceServer).SetServiceOwners(ctx, req.(*SetServiceOwnersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectsService_DecommissionService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecommissionServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServiceServer).DecommissionService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectsService_DecommissionService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServiceServer).DecommissionService(ctx, req.(*DecommissionServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectsService_TransferService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectsServiceServer).TransferService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectsService_TransferService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectsServiceServer).TransferService(ctx, req.(*TransferServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectsService_ServiceDesc is the grpc.ServiceDesc for ProjectsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "projects.v1.ProjectsService",
	HandlerType: (*ProjectsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetService",
			Handler:    _ProjectsService_GetService_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _ProjectsService_ListServices_Handler,
		},
		{
			MethodName: "CreateService",
			Handler:    _ProjectsService_CreateService_Handler,
		},
		{
			MethodName: "SetServiceOwners",
			Handler:    _ProjectsService_SetServiceOwners_Handler,
		},
		{
			MethodName: "DecommissionService",
			Handler:    _ProjectsService_DecommissionService_Handler,
		},
		{
			MethodName: "TransferService",
			Handler:    _ProjectsService_TransferService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "projects/v1/projects.proto",
}
